import assert from "node:assert/strict";
import { readFile, readdir } from "node:fs/promises";
import test from "node:test";

test("production build contains the Keeper application", async () => {
  const html = await readFile(new URL("../dist/index.html", import.meta.url), "utf8");
  const assets = await readdir(new URL("../dist/assets/", import.meta.url));
  const scripts = assets.filter((file) => file.endsWith(".js"));

  assert.match(html, /Keeper — Owner's Workshop Log/);
  assert.match(html, /\/(?:keeper-garage\/)?assets\//);
  assert.ok(scripts.length, "expected compiled JavaScript assets");

  const bundle = (await Promise.all(scripts.map((script) => readFile(
    new URL(`../dist/assets/${script}`, import.meta.url),
    "utf8",
  )))).join("\n");
  assert.match(bundle, /Urgent/);
  assert.match(bundle, /Be on the lookout/);
  assert.match(bundle, /Owner's workshop log/);
  assert.match(bundle, /Keeper Workshop Archive/);
  assert.match(bundle, /Owner-built maintenance intelligence/);
  assert.match(bundle, /3 Series \(E36\)/);
  assert.match(bundle, /3 Series \(E46\)/);
  assert.match(bundle, /5 Series \(E39\)/);
  assert.match(bundle, /Simple at first glance\. Detailed when you want it\./);
  assert.match(bundle, /M56B25 2\.5L I6/);
  assert.match(bundle, /S54B32 3\.2L I6/);
  assert.match(bundle, /S62B50 5\.0L V8/);
  assert.match(bundle, /6-speed SMG II/);
  assert.match(bundle, /Touring rear self-leveling air suspension/);
  assert.match(bundle, /Rear axle carrier panel/);
  assert.match(bundle, /keeper-theme/);
  assert.match(bundle, /Keeper — /);
  assert.match(bundle, /My Garage/);
  assert.match(bundle, /What needs attention/);
  assert.match(bundle, /Recorded spending/);
  assert.match(bundle, /Open source on GitHub/);
  assert.match(bundle, /Saved vehicles/);
  assert.match(bundle, /Add another vehicle/);
  assert.match(bundle, /Save changes/);
  assert.match(bundle, /Known issues/);
  assert.match(bundle, /View .*item maintenance list/);
  assert.match(bundle, /328i/);
  assert.match(bundle, /330i/);
  assert.match(bundle, /335i/);
  assert.match(bundle, /340i/);
  assert.match(bundle, /328d — Diesel/);
  assert.match(bundle, /330e — Plug-in Hybrid/);
  assert.match(bundle, /Each selection narrows the choices that follow/);
  assert.match(bundle, /Demo Garage/);
  assert.match(bundle, /Create Your Keeper Profile/);
  assert.match(bundle, /Forgot Password/);
  assert.match(bundle, /Add to garage/);
  assert.match(bundle, /Guest Mode · demo only/);
  assert.match(bundle, /Existing garage found · read only/);
  assert.match(bundle, /Keeper Account/);
  assert.match(bundle, /Save maintenance/);
  assert.match(bundle, /Maintenance history/);
  assert.match(bundle, /Maintenance for/);
  assert.match(bundle, /Completed work/);
  assert.match(bundle, /What does this vehicle need/);
  assert.match(bundle, /Current fluids/);
  assert.match(bundle, /No Scheduled Interval/);
  assert.match(bundle, /Add custom maintenance/);
  assert.match(bundle, /Export as PDF/);
  assert.match(bundle, /Export as image/);
  assert.match(bundle, /Search a part, symptom, issue, or common name/);
  assert.match(bundle, /No exact match found/);
  assert.match(bundle, /Track your own issue/);
  assert.match(bundle, /Remove tracked issue/);
  assert.match(bundle, /Recovery option/);
  assert.match(bundle, /Your profile/);
  assert.match(bundle, /Security/);
  assert.match(bundle, /Change Email/);
  assert.match(bundle, /Change Password/);
  assert.match(bundle, /Owner-only data/);
  assert.match(bundle, /Terms of Service/);
  assert.match(bundle, /Privacy Policy/);
});
