import type { CatalogSource, KnownIssue, VehiclePlatform } from "./catalog";

const oem = (title: string, publisher: string, url: string, note: string): CatalogSource => ({ type: "OEM", title, publisher, url, note });
const community = (title: string, publisher: string, url: string, note: string): CatalogSource => ({ type: "Community consensus", title, publisher, url, note });

const BMW_RECALLS = oem("BMW safety and emission recall lookup", "BMW of North America", "https://www.bmwusa.com/safety-and-emission-recalls.html", "Use the VIN lookup because recall eligibility follows production records, not only model year.");
const SUBARU_RECALLS = oem("Subaru vehicle recall lookup", "Subaru of America", "https://www.subaru.com/recalls.html", "Use the VIN lookup to confirm campaign eligibility and completion.");
const PORSCHE_RECALLS = oem("Porsche recall lookup", "Porsche Cars North America", "https://recall.porsche.com/", "Use the VIN lookup for open safety campaigns.");
const MAZDA_RECALLS = oem("Mazda recall information", "Mazda North American Operations", "https://www.mazdausa.com/owners/recalls", "Use the VIN lookup for open campaigns and campaign completion.");

const E9X_FORUM = community("E9x maintenance and problem archive", "E90Post owner community", "https://www.e90post.com/forums/forumdisplay.php?f=2", "Long-running owner and specialist discussions used as a symptom-discovery layer; diagnosis remains vehicle-specific.");
const SUBARU_FORUM = community("VA WRX and STI technical archive", "NASIOC owner community", "https://forums.nasioc.com/forums/forumdisplay.php?f=87", "Owner patterns are used as inspection prompts, not proof that a selected car has the condition.");
const PORSCHE_IMS = community("Porsche IMS bearing guide", "LN Engineering", "https://lnengineering.com/products/the-definitive-guide-and-faq-for-porsche-ims-bearings/", "Specialist fitment guide distinguishing M96/M97 engines from Mezger and 9A1 engines.");
const PORSCHE_996 = community("996 common-problem technical guide", "LN Engineering", "https://docs.lnengineering.com/article/159-porsche-996-common-problems-and-how-to-prevent-them", "Independent Porsche-engine specialist guidance used for inspection context.");
const PORSCHE_FORUM = community("996 and 997 technical forums", "Rennlist owner community", "https://rennlist.com/forums/911-forum-56/", "Owner reports are retained as community evidence and require inspection confirmation.");
const MIATA_GARAGE = community("Miata Garage maintenance archive", "Miata.net", "https://www.miata.net/garage/garagemaintenance.html", "Long-running owner technical archive for age-related inspection patterns.");
const MIATA_FORUM = community("MX-5 generation technical forums", "Miata.net owner community", "https://forum.miata.net/vb/", "Owner reports are used as condition-based inspection prompts.");

const platforms = (...values: VehiclePlatform[]) => ({ platforms: values });

export const EXPANDED_KNOWN_ISSUES: KnownIssue[] = [
  {
    slug: "e9x-blower-wiring-recall", system: "Electrical / HVAC", component: "Blower-regulator wiring", issue: "Blower-motor wiring safety recall", aliases: ["17V-676", "blower harness recall"], severity: "critical", urgency: "urgent", evidence: "Safety recall",
    description: "BMW recalled many 2006–2011 E9x vehicles because the blower-regulator wiring connection can degrade and overheat.", symptoms: "Burning-plastic odor, smoke near the dashboard, intermittent cabin fan, melted connector, or an open recall with no symptoms.", typicalMileage: "VIN and production-date dependent; mileage does not determine eligibility.", preventativeAction: "Check the VIN and complete any open campaign before treating an intermittent blower as a routine resistor failure.", appliesTo: { platforms: ["E9X"], years: [2006, 2007, 2008, 2009, 2010, 2011] },
    sources: [oem("Recall 17V-676: blower motor wiring", "BMW of North America / NHTSA · SIB 64 07 17", "https://static.nhtsa.gov/odi/rcl/2017/RCRIT-17V676-6485.pdf", "Official repair scope for E90, E91, E92, and E93 vehicles."), BMW_RECALLS],
  },
  {
    slug: "e9x-pcv-heater-recall", system: "Engine electrical", component: "PCV blow-by heater", issue: "PCV heater fire-risk recall", aliases: ["22V-119", "blow-by heater"], severity: "critical", urgency: "urgent", evidence: "Safety recall",
    description: "The PCV heater on specified naturally aspirated six-cylinder E9x vehicles can short internally and, in rare cases, increase fire risk.", symptoms: "Smoke or a burning smell from the engine bay, electrical faults, or an open recall without symptoms.", typicalMileage: "Production- and VIN-specific; the campaign includes listed N51, N52, and N52K vehicles.", preventativeAction: "Check the VIN and complete any open recall. Stop and shut the vehicle off if smoke or an electrical burning odor appears.", appliesTo: { platforms: ["E9X"], engines: ["N51", "N52", "N52K"] },
    sources: [oem("Recall 22V-119: PCV blow-by heater", "BMW of North America / NHTSA · SIB 11 01 22", "https://static.nhtsa.gov/odi/rcl/2022/RCRIT-22V119-6283.pdf", "Official engine and E9x body-style applicability."), BMW_RECALLS],
  },
  {
    slug: "e9x-n54-hpfp", system: "Fuel", component: "High-pressure fuel pump", issue: "N54 high-pressure fuel-pump faults", aliases: ["HPFP", "long crank", "HDP pump"], severity: "critical", urgency: "watch", evidence: "BMW bulletin",
    description: "BMW issued extended coverage and repair procedures for eligible N54 high-pressure fuel pumps.", symptoms: "Long cranking, reduced-power warning, rough running, rail-pressure faults, or stalling.", typicalMileage: "Failure is condition based; prior replacement history and pump revision matter.", preventativeAction: "Read rail-pressure faults before replacing parts and verify VIN-specific repair history or remaining coverage.", appliesTo: { platforms: ["E9X"], engines: ["N54", "N54T"] },
    sources: [oem("N54 high-pressure fuel-pump coverage", "BMW of North America · SIB 12 55 06", "https://static.nhtsa.gov/odi/tsbs/2013/MC-10149587-9999.pdf", "Official diagnostic, replacement, and coverage procedure for listed N54 E9x vehicles."), E9X_FORUM],
  },
  {
    slug: "e9x-n54-wastegates", system: "Turbo", component: "Turbocharger wastegates", issue: "N54 wastegate rattle and boost-control wear", aliases: ["wastegate rattle", "30FF", "boost leak"], severity: "important", urgency: "watch", evidence: "BMW bulletin",
    description: "BMW extended emissions coverage for eligible turbocharger failures caused by wastegate defects on listed N54 vehicles.", symptoms: "Metallic rattle, reduced boost, 30FF or related boost faults, and inconsistent power delivery.", typicalMileage: "Wear and production dependent; diagnosis must separate linkage wear from vacuum, charge-path, and control faults.", preventativeAction: "Run the BMW boost test plan and inspect vacuum and charge plumbing before condemning a turbocharger.", appliesTo: { platforms: ["E9X"], engines: ["N54", "N54T"] },
    sources: [oem("N54 turbocharger wastegate warranty extension", "BMW of North America", "https://static.nhtsa.gov/odi/tsbs/2012/SB-10045279-7898.pdf", "Official E90/E92/E93 wastegate coverage and diagnostic context."), E9X_FORUM],
  },
  {
    slug: "e9x-electric-water-pump", system: "Cooling", issue: "Electric water pump and thermostat", aliases: ["2E81", "2E82", "electric coolant pump"], severity: "critical", urgency: "watch", evidence: "Community consensus",
    description: "The electric pump and mapped thermostat can fail with age, and the dashboard may provide little warning before an overheat message.", symptoms: "High fan speed, reduced power, coolant-temperature warning, pump communication faults, or intermittent overheating.", typicalMileage: "Commonly inspected once cars are beyond roughly 70,000–120,000 miles, but failure is not mileage scheduled.", preventativeAction: "Scan pump-speed and cooling faults, verify bleeding, and stop driving for an overheat warning.", appliesTo: { platforms: ["E9X"], engines: ["N51", "N52", "N52K", "N54", "N54T", "N55"] }, sources: [E9X_FORUM],
  },
  {
    slug: "e9x-oil-leaks", system: "Engine", issue: "Valve-cover, oil-filter-housing, and oil-pan leaks", aliases: ["OFHG", "VCG", "oil pan gasket"], severity: "critical", urgency: "watch", evidence: "Community consensus",
    description: "Age-hardened seals can leak onto the exhaust, belt drive, undertray, or transmission bellhousing and should be located before parts are ordered.", symptoms: "Burning-oil odor, smoke, fresh oil around the filter housing or cover, belt contamination, or drops under the car.", typicalMileage: "Age and heat-cycle related; multiple leak sources can overlap.", preventativeAction: "Clean and trace the highest fresh leak, repair belt contamination promptly, and document oil use between services.", appliesTo: platforms("E9X"), sources: [E9X_FORUM],
  },
  {
    slug: "e9x-s65-rod-bearings", system: "Engine", component: "Connecting-rod bearings", issue: "S65 rod-bearing wear", aliases: ["M3 rod bearings", "bearing clearance"], severity: "critical", urgency: "watch", evidence: "Community consensus",
    description: "S65 specialists and owners treat rod-bearing condition as a major pre-purchase and long-term ownership risk, although wear cannot be confirmed by mileage alone.", symptoms: "Metal in the filter, bearing material in oil analysis, low oil pressure, or knock; many worn sets have no obvious warning.", typicalMileage: "History, oil temperature, use, and prior replacement matter more than a universal interval.", preventativeAction: "Review documented replacement history and obtain an S65-specialist risk assessment; do not treat one oil-analysis result as proof of bearing condition.", appliesTo: { platforms: ["E9X"], engines: ["S65"] }, sources: [E9X_FORUM],
  },
  {
    slug: "e9x-s65-throttle-actuators", system: "Engine controls", component: "Throttle actuators", issue: "S65 throttle-actuator gear and electronics wear", aliases: ["throttle actuator bank 1", "throttle actuator bank 2"], severity: "important", urgency: "watch", evidence: "Community consensus",
    description: "The two electronic throttle actuators can develop worn internal gears or electronic faults and may fail separately.", symptoms: "Limp mode, reduced power, throttle-actuator faults, or intermittent bank-specific warnings.", typicalMileage: "Age and cycle dependent; confirm which bank and failure mode is present.", preventativeAction: "Scan BMW-specific faults and test power, wiring, and actuator operation before replacing a unit.", appliesTo: { platforms: ["E9X"], engines: ["S65"] }, sources: [E9X_FORUM],
  },
  {
    slug: "e9x-m57-emissions", system: "Diesel emissions", issue: "M57Y SCR, DPF, EGR, and carbon-loading faults", aliases: ["335d DEF countdown", "DPF regeneration", "SCR efficiency"], severity: "critical", urgency: "watch", evidence: "Community consensus",
    description: "Short trips, thermostat faults, soot loading, DEF hardware, NOx sensors, and intake deposits can interact and create expensive diesel-emissions complaints.", symptoms: "Reduced power, frequent regeneration, poor fuel economy, SCR warnings, no-start countdown, or airflow and boost faults.", typicalMileage: "Use-pattern and condition dependent rather than a single interval.", preventativeAction: "Use BMW diesel diagnostics to identify the root cause before forcing regeneration or replacing emissions parts.", appliesTo: { platforms: ["E9X"], engines: ["M57Y"] }, sources: [E9X_FORUM],
  },

  {
    slug: "va-wrx-fuel-pump-recall", system: "Fuel", component: "Low-pressure fuel pump", issue: "2018–2019 WRX fuel-pump impeller recall", aliases: ["WRG-21", "21V-587"], severity: "critical", urgency: "urgent", evidence: "Safety recall",
    description: "Certain 2018–2019 WRX fuel-pump impellers can deform and make the pump inoperative, potentially causing an engine stall.", symptoms: "Rough running, warning light, failure to start, engine stall, or an open campaign without symptoms.", typicalMileage: "Limited to specific production records; not every WRX in the model-year range is affected.", preventativeAction: "Check the VIN and complete campaign WRG-21 if open.", appliesTo: { platforms: ["VA"], years: [2018, 2019], trims: ["WRX"] },
    sources: [oem("WRG-21 fuel-pump impeller recall", "Subaru of America / NHTSA", "https://static.nhtsa.gov/odi/tsbs/2021/MC-10201799-0001.pdf", "Official campaign bulletin and production scope."), SUBARU_RECALLS],
  },
  {
    slug: "va-wrx-release-bearing", system: "Clutch", component: "Clutch release bearing", issue: "WRX clutch release-bearing noise and wear", aliases: ["throwout bearing", "TOB", "clutch squeak"], severity: "important", urgency: "watch", evidence: "Manufacturer bulletin",
    description: "Subaru revised the clutch release bearing and published inspection and lubrication guidance for 2015–2020 WRX 2.0 DIT models.", symptoms: "Chirp, squeak, rumble, or pedal-related noise that changes when the clutch is pressed.", typicalMileage: "Cycle and use dependent; noise source must be isolated from the fork, pivot, pilot bearing, and gearbox.", preventativeAction: "Inspect all release-fork contact points and use the revised bearing and specified grease when repair is confirmed.", appliesTo: { platforms: ["VA"], trims: ["WRX"], engines: ["FA20DIT"], transmissions: ["6-speed manual"] },
    sources: [oem("Clutch release-bearing design change", "Subaru of America · TSB 03-78-17R", "https://static.nhtsa.gov/odi/tsbs/2021/MC-10186366-0001.pdf", "Official applicability and service procedure."), SUBARU_FORUM],
  },
  {
    slug: "va-fa20dit-carbon", system: "Intake", issue: "FA20DIT direct-injection intake-valve deposits", aliases: ["walnut blasting", "carbon buildup", "cold-start stumble"], severity: "important", urgency: "watch", evidence: "Community consensus",
    description: "Direct injection does not wash the intake valves with fuel, so deposits can accumulate depending on use, oil vapor, and maintenance history.", symptoms: "Uneven cold idle, hesitation, misfire, reduced response, or deposits confirmed by borescope.", typicalMileage: "Usage dependent; diagnose before cleaning because ignition, boost, and fueling faults can feel similar.", preventativeAction: "Check fuel trims, misfire data, plugs, boost leaks, and valve condition before authorizing mechanical cleaning.", appliesTo: { platforms: ["VA"], engines: ["FA20DIT"] }, sources: [SUBARU_FORUM],
  },
  {
    slug: "va-turbo-oil-control", system: "Engine / turbo", issue: "Turbo-engine oil level, pickup, and bearing-risk monitoring", aliases: ["rod bearing", "oil starvation", "oil pickup"], severity: "critical", urgency: "watch", evidence: "Community consensus",
    description: "Both VA turbo-engine families are sensitive to correct oil level, temperature, contamination, tuning quality, and sustained-load history; owner reports alone cannot diagnose bearing condition.", symptoms: "Low oil level, metallic filter debris, oil-pressure warning, knock, turbo noise, or unexplained oil consumption.", typicalMileage: "Use and modification dependent; track use and poor calibration increase the need for inspection.", preventativeAction: "Keep oil at the correct level, document consumption, inspect cut-open filters, and stop immediately for oil-pressure or knock symptoms.", appliesTo: platforms("VA"), sources: [SUBARU_FORUM],
  },
  {
    slug: "va-ej257-ringlands", system: "Engine", component: "Pistons and combustion sealing", issue: "EJ257 ringland and detonation damage", aliases: ["ringland failure", "low compression", "STI piston"], severity: "critical", urgency: "watch", evidence: "Community consensus",
    description: "EJ257 owner and specialist reports repeatedly associate poor fuel, detonation, unsafe calibration, and high heat with piston ringland damage; not every stock engine develops it.", symptoms: "Misfire, oil consumption, smoke, low compression, excessive crankcase pressure, or knock events in logs.", typicalMileage: "Condition, tune, fuel, and use dependent.", preventativeAction: "Verify calibration and fuel quality, investigate knock and misfires promptly, and confirm with compression and leak-down testing before engine work.", appliesTo: { platforms: ["VA"], engines: ["EJ257"] }, sources: [SUBARU_FORUM],
  },
  {
    slug: "va-hubs-studs", system: "Chassis", issue: "Wheel-stud, hub-bearing, and alignment wear", aliases: ["wheel bearing hum", "broken wheel stud"], severity: "critical", urgency: "watch", evidence: "Community consensus",
    description: "Repeated wheel service, corrosion, impacts, and track use can damage studs or accelerate hub-bearing and alignment wear.", symptoms: "Hum that changes with cornering load, wheel play, damaged threads, vibration, or uneven tire wear.", typicalMileage: "Use and service-practice dependent.", preventativeAction: "Hand-start lug nuts, torque clean threads correctly, and inspect hubs and alignment after impacts or bearing-noise complaints.", appliesTo: platforms("VA"), sources: [SUBARU_FORUM],
  },

  {
    slug: "porsche-m96-m97-ims", system: "Engine", component: "Intermediate-shaft bearing", issue: "M96/M97 IMS-bearing risk", aliases: ["IMS", "intermediate shaft", "single-row IMS"], severity: "critical", urgency: "watch", evidence: "Community consensus",
    description: "The serviceable and later non-serviceable IMS bearing designs differ by engine and production date. Mezger and 9A1 engines do not use the same failure-prone arrangement.", symptoms: "Metal or seal debris in the filter, abnormal rear-engine noise, cam timing deviation, or oil leakage at the IMS flange; failure can occur without a clear warning.", typicalMileage: "Engine number, bearing design, history, and time matter more than a universal interval.", preventativeAction: "Identify the engine and bearing design before planning work; inspect filter media and obtain a Porsche-specialist assessment rather than replacing parts by model year alone.", appliesTo: { platforms: ["9961", "9962", "9971"], engines: ["M96-3.4", "M96-3.6", "M96-M97 Carrera", "M96-M97 Carrera S"] }, sources: [PORSCHE_IMS],
  },
  {
    slug: "porsche-m96-m97-bore-scoring", system: "Engine", component: "Cylinder bores", issue: "M96/M97 cylinder bore scoring", aliases: ["bore score", "piston slap", "sooty tailpipe"], severity: "critical", urgency: "watch", evidence: "Community consensus",
    description: "Cylinder-wall and piston-skirt damage is a documented specialist inspection concern on M96/M97 engines, with risk varying by displacement, use, temperature, and history.", symptoms: "Ticking that follows engine speed, increasing oil use, one sooty exhaust outlet, metal in the filter, or scuffing seen by properly oriented borescope.", typicalMileage: "Condition based; a quiet engine or low mileage does not prove bore condition.", preventativeAction: "Use a warm inspection, oil-use history, filter inspection, and crankcase-side borescope images before drawing conclusions.", appliesTo: { platforms: ["9961", "9962", "9971"], engines: ["M96-3.4", "M96-3.6", "M96-M97 Carrera", "M96-M97 Carrera S"] }, sources: [PORSCHE_996, community("997.1 market and inspection guidance", "Porsche Club of America", "https://mediaassets.pca.org/pages/docs/mainweb/pdf/71963_2021.01_mart_market_dashboard_997.1.pdf", "PCA specifically flags bore-scoring inspection and pre-purchase evaluation." )],
  },
  {
    slug: "porsche-m96-m97-aos-rms", system: "Engine", issue: "Air-oil separator and rear-main-seal leaks", aliases: ["AOS", "RMS", "rear main seal", "smoke on startup"], severity: "important", urgency: "watch", evidence: "Community consensus",
    description: "A failing air-oil separator can create excessive crankcase vacuum and smoke, while rear engine leaks require careful source tracing before assuming the RMS is responsible.", symptoms: "Heavy smoke, whistling, difficult oil-cap removal, mixture faults, or oil at the engine-transmission joint.", typicalMileage: "Age and diaphragm/seal condition dependent.", preventativeAction: "Measure crankcase vacuum and cleanly trace the leak source; inspect the clutch for contamination when the gearbox is removed.", appliesTo: { platforms: ["9961", "9962", "9971"], engines: ["M96-3.4", "M96-3.6", "M96-M97 Carrera", "M96-M97 Carrera S"] }, sources: [PORSCHE_996, PORSCHE_FORUM],
  },
  {
    slug: "porsche-mezger-coolant-pipes", system: "Cooling", component: "Bonded coolant-pipe fittings", issue: "Mezger coolant-pipe fitting leakage", aliases: ["pinned coolant pipes", "glued coolant fittings"], severity: "critical", urgency: "watch", evidence: "Manufacturer bulletin",
    description: "Porsche and NHTSA investigated adhesive-bonded coolant fittings on 2001–2011 Turbo, GT2, and GT3 engines; leakage rates varied by production period and heat exposure.", symptoms: "Coolant odor, sudden coolant loss, residue around bonded fittings, puddles, or an overheat warning.", typicalMileage: "Production, heat-cycle, track-use, coolant, and prior repair dependent.", preventativeAction: "Inspect all bonded fittings and repair with a recognized Porsche-specialist method before track use or after any leakage is found.", appliesTo: { platforms: ["9962", "9971", "9972"], engines: ["Mezger-Turbo", "Mezger-GT2", "Mezger-GT3", "Mezger Turbo", "Mezger GT3", "Mezger GT3 RS", "Mezger GT2", "Mezger GT3 RS 4.0", "Mezger GT2 RS"] },
    sources: [oem("NHTSA investigation PE13-009: Porsche coolant fittings", "NHTSA Office of Defects Investigation", "https://static.nhtsa.gov/odi/inv/2013/INCLA-PE13009-5428.PDF", "Official investigation covering 2001–2011 Turbo, GT2, and GT3 coolant-pipe fittings."), PORSCHE_RECALLS],
  },
  {
    slug: "porsche-front-radiator-debris", system: "Cooling / A/C", issue: "Front radiator and condenser debris corrosion", aliases: ["radiator leaves", "condenser corrosion"], severity: "important", urgency: "watch", evidence: "Community consensus",
    description: "Leaves and road debris collect behind the front intakes, trap moisture, restrict airflow, and corrode radiators or A/C condensers.", symptoms: "Coolant or refrigerant loss, damp debris in the corners, fan activity, rising temperature, or weak A/C.", typicalMileage: "Time, climate, and storage dependent.", preventativeAction: "Remove the front liners or bumper as appropriate for a complete inspection and clean without bending fins.", appliesTo: { platforms: ["9961", "9962", "9971", "9972"] }, sources: [PORSCHE_FORUM],
  },
  {
    slug: "porsche-suspension-arms-mounts", system: "Chassis", issue: "Control-arm, top-mount, and damper wear", aliases: ["coffin arms", "tuning forks", "top mounts"], severity: "critical", urgency: "watch", evidence: "Community consensus",
    description: "Aged bushings, ball joints, dampers, and mounts can degrade geometry and braking stability even when the car still feels tight on a short drive.", symptoms: "Clunks, wandering, uneven tire wear, braking instability, cracked bushings, or leaking dampers.", typicalMileage: "Age, roads, wheel fitment, and use dependent.", preventativeAction: "Inspect the chassis as a system and align only after worn joints, mounts, tires, and dampers are corrected.", appliesTo: { platforms: ["9961", "9962", "9971", "9972"] }, sources: [PORSCHE_FORUM],
  },
  {
    slug: "porsche-9972-pdk-sensors", system: "Transmission", component: "PDK sensors and mechatronics", issue: "997.2 PDK sensor and gear-selection faults", aliases: ["P1731", "P1732", "gearbox emergency operation"], severity: "critical", urgency: "watch", evidence: "Manufacturer bulletin",
    description: "Porsche published diagnostic flow charts for PDK electrical, distance, speed, pressure, temperature, and engagement faults instead of treating every warning as a complete gearbox failure.", symptoms: "Gearbox emergency operation, refusal to select a gear, gear skip, harsh shift, or stored P17xx/P176x faults.", typicalMileage: "Fault and component dependent.", preventativeAction: "Record all PDK faults and operating conditions and follow the Porsche flow chart before authorizing a gearbox or control-unit replacement.", appliesTo: { platforms: ["9972"], transmissions: ["7-speed PDK"] },
    sources: [oem("PDK fault-code diagnostic flow charts", "Porsche Cars North America · TI 35/09", "https://static.nhtsa.gov/odi/tsbs/2012/SB-10043332-8620.pdf", "Official diagnostic routes for gear engagement and sensor faults."), oem("PDK temperature-sensor repair", "Porsche Cars North America · TI 90/11", "https://static.nhtsa.gov/odi/tsbs/2013/SB-10052517-4176.pdf", "Official temperature-sensor fault and repair scope for 2009–2011 PDK cars.")],
  },
  {
    slug: "porsche-9972-dfi-fueling-carbon", system: "Fuel / intake", issue: "9A1 direct-injection fueling and intake deposits", aliases: ["DFI carbon", "high pressure fuel pump", "cold misfire"], severity: "important", urgency: "watch", evidence: "Community consensus",
    description: "Direct-injection fuel-pressure faults, injector condition, ignition wear, air leaks, and intake-valve deposits can create overlapping drivability symptoms.", symptoms: "Long crank, cold misfire, hesitation, fuel-pressure faults, or uneven idle.", typicalMileage: "Condition and use dependent.", preventativeAction: "Review pressure targets, misfire counters, plugs, coils, injectors, and intake condition before replacing a high-pressure pump or cleaning valves.", appliesTo: { platforms: ["9972"], engines: ["MA1 DFI Carrera", "MA1 DFI Carrera S", "MA1 DFI GTS", "997.2 Turbo DFI"] }, sources: [PORSCHE_FORUM],
  },

  {
    slug: "miata-na-short-nose-crank", system: "Engine", component: "Crankshaft nose and keyway", issue: "Early 1.6L short-nose crank keyway damage", aliases: ["SNC", "wobbling crank pulley", "short nose crank"], severity: "critical", urgency: "watch", evidence: "Community consensus",
    description: "Some early 1.6L engines can develop crank pulley and keyway damage after incorrect timing-belt pulley installation or bolt torque.", symptoms: "Wobbling crank pulley, drifting ignition timing, belt noise, damaged keyway, or loose crank bolt.", typicalMileage: "Primarily an early-production and prior-service issue, not normal scheduled wear.", preventativeAction: "Observe pulley runout and verify crank-nose condition before timing work; use the exact washer, key, bolt, and torque procedure.", appliesTo: { platforms: ["NA"], years: [1990, 1991], engines: ["B6"] }, sources: [MIATA_GARAGE, MIATA_FORUM],
  },
  {
    slug: "miata-na-cas-oil-leak", system: "Engine", issue: "CAS O-ring and valve-cover oil leaks", aliases: ["cam angle sensor O-ring", "oil at rear of head"], severity: "important", urgency: "watch", evidence: "Community consensus",
    description: "The cam-angle-sensor O-ring and valve-cover gasket harden with age and can leak onto the rear of the engine and transmission.", symptoms: "Burning-oil smell, wetness behind the cylinder head, oil on heater hoses, or drops near the bellhousing.", typicalMileage: "Age and heat-cycle dependent.", preventativeAction: "Trace the highest fresh leak and mark distributor/CAS position correctly before removal.", appliesTo: platforms("NA"), sources: [MIATA_GARAGE, MIATA_FORUM],
  },
  {
    slug: "miata-na-cooling-age", system: "Cooling", issue: "Aged radiator, water plug, and coolant hoses", aliases: ["brown radiator", "cursed water plug", "heater hose failure"], severity: "critical", urgency: "watch", evidence: "Community consensus",
    description: "Original plastic radiators, small rear coolant caps, hoses, and clamps are now age-critical on NA cars and can fail quickly once brittle.", symptoms: "Brown or green radiator plastic, coolant odor, crusted fittings, soft or swollen hoses, leakage, or rising temperature.", typicalMileage: "Calendar age is the primary risk.", preventativeAction: "Pressure-test cold, inspect every hose and plug, and stop immediately for overheating.", appliesTo: platforms("NA"), sources: [MIATA_GARAGE, MIATA_FORUM],
  },
  {
    slug: "miata-na-water-rust", system: "Body", issue: "Soft-top drains, rain rail, and sill rust", aliases: ["rocker rust", "clogged drains", "wet trunk"], severity: "critical", urgency: "watch", evidence: "Community consensus",
    description: "Blocked drains or a damaged rain rail can retain water inside the sills and trunk, causing hidden corrosion.", symptoms: "Water behind seats or in the trunk, slow drain flow, bubbling paint, rust at pinch seams, or damp carpet.", typicalMileage: "Age, climate, storage, and top condition dependent.", preventativeAction: "Inspect with the trim lifted where safe, clear drains using non-damaging methods, and address structural corrosion before cosmetic work.", appliesTo: platforms("NA"), sources: [MIATA_GARAGE, MIATA_FORUM],
  },
  {
    slug: "miata-nb-thrust-bearing", system: "Engine", component: "Crankshaft thrust bearing", issue: "1999–2000 crankshaft end-play concern", aliases: ["number 4 thrust bearing", "crank walk"], severity: "critical", urgency: "watch", evidence: "Community consensus",
    description: "A subset of early NB engines developed excessive crankshaft end play associated with the thrust bearing; most reports center on 1999–2000 cars.", symptoms: "Excess crank movement when the clutch is operated, clutch engagement changes, crank sensor issues, or internal engine noise.", typicalMileage: "Many reported failures occurred earlier in life, but inspection is still more useful than assuming status from mileage.", preventativeAction: "Measure crankshaft end play correctly during a pre-purchase or symptom-driven inspection.", appliesTo: { platforms: ["NB"], years: [1999, 2000], engines: ["BP-4W"] }, sources: [community("Common NB issues discussion", "Miata.net owner community", "https://forum.miata.net/vb/showthread.php?t=552185", "Owner-compiled inspection list with corrections and fitment discussion."), MIATA_FORUM],
  },
  {
    slug: "miata-nb-coils-catalyst", system: "Ignition / emissions", issue: "NB ignition-coil failure and catalyst damage", aliases: ["NB coil pack", "pre-cat", "misfire"], severity: "critical", urgency: "watch", evidence: "Community consensus",
    description: "A sustained coil or ignition misfire can send unburned fuel into the close-coupled catalyst on applicable cars and damage the catalyst core.", symptoms: "Flashing check-engine light, misfire, loss of power, sulfur odor, glowing catalyst, or exhaust restriction.", typicalMileage: "Age and heat dependent; do not continue driving with a flashing MIL.", preventativeAction: "Stop for a flashing warning light, identify the failed cylinder, and inspect catalyst restriction after a severe misfire event.", appliesTo: platforms("NB"), sources: [community("Common NB issues discussion", "Miata.net owner community", "https://forum.miata.net/vb/showthread.php?t=552185", "Recurring ignition and catalyst owner patterns."), MIATA_FORUM],
  },
  {
    slug: "miata-nb-frame-rail-rust", system: "Body / chassis", issue: "Double-skin front frame-rail corrosion", aliases: ["NB frame rail rust", "front chassis rail rust"], severity: "critical", urgency: "watch", evidence: "Community consensus",
    description: "Moisture and debris can corrode the NB's double-skin front chassis rails from inside, leaving more damage than surface appearance suggests.", symptoms: "Swelling seams, flaking metal, soft jack or suspension areas, rust near the anti-roll-bar mounts, or previous patch repairs.", typicalMileage: "Climate, winter use, and drainage dependent.", preventativeAction: "Inspect all sides and internal condition before purchase or alignment work; structural repair should be evaluated by a qualified fabricator.", appliesTo: platforms("NB"), sources: [community("Common NB issues discussion", "Miata.net owner community", "https://forum.miata.net/vb/showthread.php?t=552185", "Includes owner inspection reports on double-skin rail corrosion."), MIATA_FORUM],
  },
  {
    slug: "miata-nb-water-ingress", system: "Body", issue: "Rain-rail, drain, and trunk water ingress", aliases: ["wet NB trunk", "soft top drain", "third brake light leak"], severity: "important", urgency: "watch", evidence: "Community consensus",
    description: "A damaged rain rail, blocked drains, top seals, or lamp seals can put water behind the seats or into the trunk and accelerate corrosion.", symptoms: "Damp carpet, mildew, water in trunk wells, slow drains, or corrosion around seams.", typicalMileage: "Age and weather dependent.", preventativeAction: "Water-test by zones, clear drains gently, and repair the actual entry path before drying and treating corrosion.", appliesTo: platforms("NB"), sources: [community("Common NB issues discussion", "Miata.net owner community", "https://forum.miata.net/vb/showthread.php?t=552185", "Owner troubleshooting for rain rail and drain leakage."), MIATA_FORUM],
  },
  {
    slug: "miata-nc-expansion-tank", system: "Cooling", component: "Pressurized expansion tank", issue: "NC coolant expansion-tank aging and cracking", aliases: ["coolant bottle", "yellow expansion tank"], severity: "critical", urgency: "watch", evidence: "Community consensus",
    description: "The pressurized plastic tank becomes brittle and discolored with age; cracking or cap-area failure can rapidly release coolant.", symptoms: "Yellowed or crazed plastic, coolant smell, residue at seams or cap, falling level, or an overheat warning.", typicalMileage: "Calendar age and heat cycles matter more than mileage.", preventativeAction: "Inspect the cold tank closely and replace a cracked or severely aged unit before it becomes a pressure failure.", appliesTo: platforms("NC"), sources: [MIATA_FORUM],
  },
  {
    slug: "miata-nc-differential-whine", system: "Driveline", component: "Rear differential", issue: "2006–2013 differential gear whine", aliases: ["NC diff whine", "rear gear noise"], severity: "important", urgency: "watch", evidence: "Manufacturer bulletin",
    description: "Mazda documented abnormal rear-differential wear caused by excess production lapping compound on specified vehicles.", symptoms: "Speed-related whine from the rear that changes with load or coast.", typicalMileage: "VIN and condition dependent; tire and bearing noise must be ruled out.", preventativeAction: "Confirm the sound source under load and compare the VIN to Mazda's production cutoff before replacing a differential.", appliesTo: { platforms: ["NC"], years: [2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013] },
    sources: [oem("Rear differential whine", "Mazda North American Operations · TSB 03-002/16", "https://static.nhtsa.gov/odi/tsbs/2016/SB-10101085-2532.pdf", "Official symptom, production cutoff, and repair direction."), MIATA_FORUM],
  },
  {
    slug: "miata-nc-water-management", system: "Body", issue: "Cowl and convertible drain water ingress", aliases: ["wet NC floor", "roof drains", "cowl grommets"], severity: "important", urgency: "watch", evidence: "Community consensus",
    description: "Blocked roof drains, cowl seals, or body plugs can wet the cabin and hidden modules, with different paths on soft-top and retractable-hardtop cars.", symptoms: "Wet carpet, sloshing, mildew, fogging, water behind seats, or electrical faults after rain.", typicalMileage: "Debris, seal age, and storage dependent.", preventativeAction: "Trace with a controlled water test and clear the correct drain path without puncturing hoses or seals.", appliesTo: platforms("NC"), sources: [MIATA_FORUM],
  },
  {
    slug: "miata-nd-early-manual-transmission", system: "Transmission", component: "Second and third gears", issue: "Early ND manual-transmission gear damage", aliases: ["ND1 gearbox", "2nd gear grind", "3rd gear failure"], severity: "critical", urgency: "watch", evidence: "Manufacturer bulletin",
    description: "Mazda revised second- and third-gear construction after documented grinding, inability to select a gear, and abnormal neutral noise on specified early 2016–2017 cars.", symptoms: "Grinding on 1–2 or 2–3 shifts, refusal to select second or third, or unusual neutral noise.", typicalMileage: "VIN, transmission serial number, and prior replacement history are more important than mileage.", preventativeAction: "Check VIN and gearbox serial history and obtain diagnosis before the condition progresses; do not confuse normal deceleration rattle with gear damage.", appliesTo: { platforms: ["ND"], years: [2016, 2017], transmissions: ["6-speed manual"] },
    sources: [oem("Grinding or unusual manual-transmission noise", "Mazda North American Operations · TSB 05-007/16", "https://static.nhtsa.gov/odi/tsbs/2016/MC-10186245-9999.pdf", "Official VIN cutoff, symptoms, and revised gear design."), MAZDA_RECALLS],
  },
  {
    slug: "miata-nd-soft-top-contact", system: "Body", issue: "ND soft-top fabric, frame, and trim contact", aliases: ["top rubbing", "seat-back garnish scratch", "inner cloth loose"], severity: "important", urgency: "watch", evidence: "Manufacturer bulletin",
    description: "Mazda published multiple soft-top adjustments and retainers for early ND fabric contact, loose inner cloth, and folded-top interference.", symptoms: "Abraded fabric, loose inner liner, rear-window obstruction, scratches behind the seats, or binding while lowering the top.", typicalMileage: "Production and top-adjustment dependent; applies only when the vehicle has the fabric soft top.", preventativeAction: "Inspect fabric clearance during slow operation and use the applicable Mazda adjustment or protector procedure before a rub becomes a hole.", appliesTo: { platforms: ["ND"] },
    sources: [oem("Convertible-top inner cloth repair", "Mazda North American Operations · TSB 09-021/16", "https://static.nhtsa.gov/odi/tsbs/2016/SB-10093144-6903.pdf", "Official loose-inner-cloth repair."), oem("Convertible-top contact adjustment", "Mazda North American Operations · TSB 09-018/16", "https://static.nhtsa.gov/odi/tsbs/2016/SB-10091864-6903.pdf", "Official folded-top clearance correction.")],
  },
  {
    slug: "miata-nd-water-drains", system: "Body", issue: "ND roof-drain and cabin water management", aliases: ["wet ND carpet", "roof drain filter", "water behind seat"], severity: "important", urgency: "watch", evidence: "Community consensus",
    description: "Soft-top and RF drainage paths can collect debris or become displaced, allowing water into the cabin or rear storage areas.", symptoms: "Wet carpet, mildew, water behind seats, sloshing, fogging, or damp trim after rain.", typicalMileage: "Environment and storage dependent.", preventativeAction: "Inspect after heavy rain, clean the correct drain filters gently, and verify hose routing before replacing seals.", appliesTo: platforms("ND"), sources: [MIATA_FORUM],
  },
  {
    slug: "miata-nd-windshield-glass", system: "Body / glass", issue: "Windshield edge damage and stress cracking", aliases: ["ND windshield crack", "thin windshield"], severity: "important", urgency: "watch", evidence: "Community consensus",
    description: "ND owners report cracks beginning from chips or glass edges; body opening, prior installation, and impact evidence must be inspected before calling a crack spontaneous.", symptoms: "Chip spreading rapidly, edge-origin crack, wind noise, water entry, or camera/sensor calibration concerns after replacement.", typicalMileage: "Impact and installation dependent.", preventativeAction: "Repair chips promptly and use a glass installer familiar with trim, sensor calibration, and body-opening inspection.", appliesTo: platforms("ND"), sources: [MIATA_FORUM],
  },

  {
    slug: "f10-vanos-bolt-recall", system: "Engine", component: "VANOS housing bolts", issue: "2011 VANOS-bolt safety recall", aliases: ["14V-176", "camshaft housing bolts"], severity: "critical", urgency: "urgent", evidence: "Safety recall",
    description: "BMW recalled specified 2011 528i and 535i vehicles because VANOS housing bolts can loosen or break and cause reduced power or stalling.", symptoms: "Drivetrain warning, reduced power, rough running, engine noise, stalling, or an open recall with no symptoms.", typicalMileage: "VIN specific and not mileage based.", preventativeAction: "Check the VIN and complete any open recall before diagnosing a related drivability complaint.", appliesTo: { platforms: ["F10"], years: [2011], engines: ["N52", "N55"] },
    sources: [oem("Recall 14V-176: VANOS housing bolts", "BMW of North America / NHTSA", "https://static.nhtsa.gov/odi/rcl/2014/RCAK-14V176-2408.pdf", "Official model-year and engine safety recall scope."), BMW_RECALLS],
  },
  {
    slug: "f10-n20-timing-chain", system: "Engine", component: "Timing and oil-pump drive chains", issue: "N20 timing-chain and oil-pump-drive wear", aliases: ["N20 chain guides", "timing whine"], severity: "critical", urgency: "watch", evidence: "BMW bulletin",
    description: "BMW issued VIN-specific extended coverage for timing-chain and oil-pump-drive components on eligible N20 vehicles.", symptoms: "Whine, chain rattle, timing faults, oil-pressure warning, or plastic debris in the filter.", typicalMileage: "Production, VIN, oil history, and condition dependent.", preventativeAction: "Verify eligibility and build date, inspect filter debris, and stop for oil-pressure or timing faults.", appliesTo: { platforms: ["F10"], engines: ["N20"] },
    sources: [oem("N20/N26 timing-chain limited warranty extension", "BMW of North America · SIB 11 03 17", "https://bmwrepairguide.com/sib/110317.pdf", "Official affected-production and covered-component guidance."), BMW_RECALLS],
  },
  {
    slug: "f10-n55-cooling-oil-leaks", system: "Engine / cooling", issue: "N55 electric water pump and oil-gasket leaks", aliases: ["OFHG", "valve cover", "electric coolant pump"], severity: "critical", urgency: "watch", evidence: "Community consensus",
    description: "N55 ownership commonly involves electric-pump faults and age-hardened valve-cover or oil-filter-housing seals; oil near the belt raises the consequence.", symptoms: "High fan, overheat warning, coolant faults, burning-oil odor, oil around the housing, or contaminated belt.", typicalMileage: "Age, heat cycle, and service-history dependent.", preventativeAction: "Scan pump operation, pressure-test cooling loss, and repair belt contamination promptly after locating the leak source.", appliesTo: { platforms: ["F10"], engines: ["N55"] }, sources: [community("F10 owner technical forum", "Bimmerpost F10 community", "https://f10.5post.com/forums/", "Recurring owner and specialist inspection patterns." )],
  },
  {
    slug: "f10-n63-care-package", system: "Engine", issue: "N63 injectors, ventilation, turbo seals, timing, and oil consumption", aliases: ["N63 CCP", "Customer Care Package", "valve stem seals"], severity: "critical", urgency: "watch", evidence: "BMW bulletin",
    description: "BMW's N63 Customer Care Package and later settlement procedures addressed multiple drivability, air-path, fuel, timing, leakage, and oil-consumption inspection points on early F10 550i vehicles.", symptoms: "Excess oil use, smoke, misfire, rough running, fuel odor, timing faults, low battery, or turbo-area leakage.", typicalMileage: "Production, repair history, and current condition dependent; the package was not a safety recall.", preventativeAction: "Review VIN-specific CCP and repair history, document oil use, and follow the BMW diagnostic checklist rather than replacing one suspected component at a time.", appliesTo: { platforms: ["F10"], engines: ["N63"] },
    sources: [oem("N63 Engine Customer Care Package", "BMW of North America · SIB 11 06 14", "https://static.nhtsa.gov/odi/tsbs/2015/MC-10147593-9999.pdf", "Official six-point inspection and component list for early F10 N63 vehicles."), oem("N63 oil-consumption diagnosis and repair", "BMW of North America · SIB 01 21 18", "https://static.nhtsa.gov/odi/tsbs/2019/MC-10163026-9999.pdf", "Official class-vehicle diagnosis and repair process.")],
  },
  {
    slug: "f10-diesel-egr-recall", system: "Diesel emissions", component: "EGR cooler", issue: "535d EGR-cooler safety recall", aliases: ["18V-755", "21V-907", "N57 EGR cooler"], severity: "critical", urgency: "urgent", evidence: "Safety recall",
    description: "An internally leaking EGR cooler can mix coolant with soot, damage the intake manifold, and in rare cases increase fire risk.", symptoms: "Coolant loss, exhaust odor, reduced power, unusual engine-bay noise, smoke, or an open campaign.", typicalMileage: "VIN and production-date based.", preventativeAction: "Check the VIN and complete every open EGR campaign; stop and arrange inspection for smoke or unexplained coolant loss.", appliesTo: { platforms: ["F10"], engines: ["N57TU"] },
    sources: [oem("Recall 18V-755: diesel EGR cooler", "BMW of North America / NHTSA", "https://static.nhtsa.gov/odi/rcl/2018/RCRIT-18V755-9283.pdf", "Official F10 535d scope, symptoms, risk, and remedy."), BMW_RECALLS],
  },
  {
    slug: "f10-low-pressure-fuel-pump", system: "Fuel", component: "In-tank fuel-delivery module", issue: "Early F10 in-tank fuel-pump coverage", aliases: ["LPFP", "fuel delivery module"], severity: "critical", urgency: "watch", evidence: "BMW bulletin",
    description: "BMW extended component-specific coverage for the in-tank pump on eligible early F10 535i and 550i vehicles.", symptoms: "Long crank, loss of power, rough running, low-pressure fuel faults, stall, or no-start.", typicalMileage: "VIN specific; model year alone does not establish eligibility.", preventativeAction: "Test low-side pressure and power supply and check VIN coverage before replacing the module.", appliesTo: { platforms: ["F10"], years: [2011], engines: ["N55", "N63"] },
    sources: [oem("In-tank fuel-delivery module warranty extension", "BMW of North America · SIB 01 05 15", "https://static.nhtsa.gov/odi/tsbs/2016/MC-10146988-9999.pdf", "Official eligible F10 engine and production information.")],
  },
  {
    slug: "f10-water-vapor-electronics", system: "Body / electrical", issue: "Door vapor barriers, drains, and low-voltage faults", aliases: ["wet F10 carpet", "battery discharge", "comfort access faults"], severity: "important", urgency: "watch", evidence: "Community consensus",
    description: "Water entry and an aging or incorrectly registered battery can create overlapping body, comfort, and module faults on an electronically dense F10.", symptoms: "Wet carpet, window or lock faults, battery-discharge warnings, multiple intermittent messages, or water in body cavities.", typicalMileage: "Seal, drain, battery age, and storage dependent.", preventativeAction: "Locate water entry, test battery capacity and charging, scan all modules, and register the correct replacement battery.", appliesTo: platforms("F10"), sources: [community("F10 owner technical forum", "Bimmerpost F10 community", "https://f10.5post.com/forums/", "Long-running body, battery, and electrical diagnostic discussions." )],
  },
  {
    slug: "f10-activehybrid-cooling", system: "Hybrid", issue: "ActiveHybrid 5 high-voltage cooling and 12-volt dependency", aliases: ["ActiveHybrid drivetrain warning", "HV battery cooling"], severity: "critical", urgency: "watch", evidence: "Community consensus",
    description: "The hybrid system depends on healthy thermal management, power electronics, and 12-volt supply; unrelated low-voltage faults can produce broad hybrid warnings.", symptoms: "Drivetrain or high-voltage warning, electric operation unavailable, charging-state faults, cooling noise, or multiple low-voltage messages.", typicalMileage: "Fault, temperature, battery age, and storage dependent.", preventativeAction: "Do not open high-voltage components; test the 12-volt system and use BMW hybrid-capable diagnostics and trained service personnel.", appliesTo: { platforms: ["F10"], trims: ["ActiveHybrid 5"] }, sources: [community("F10 ActiveHybrid owner archive", "Bimmerpost F10 community", "https://f10.5post.com/forums/", "Owner symptom patterns used only to direct qualified diagnostics." )],
  },
  {
    slug: "f10m5-oil-pump-recall", system: "Engine", component: "Engine oil pump", issue: "Early 2013 M5 oil-pump recall", aliases: ["12V-475", "S63T oil pump"], severity: "critical", urgency: "urgent", evidence: "Safety recall",
    description: "Certain early-production 2013 M5 oil-pump driveshafts could separate, cause immediate loss of oil pressure, and damage the engine.", symptoms: "Oil-pressure warning, engine noise, loss of power, or an open recall with no symptoms.", typicalMileage: "Limited to specified July–September 2012 production; VIN verification is required.", preventativeAction: "Stop the engine immediately for an oil-pressure warning and check the VIN for completed recall 12V-475.", appliesTo: { platforms: ["F10M5"], years: [2013], engines: ["S63TU"] },
    sources: [oem("Recall 12V-475: replace engine oil pump", "BMW of North America / NHTSA · SIB 11 09 12", "https://static.nhtsa.gov/odi/rcl/2012/RCMN-12V475-5867.pdf", "Official affected production and failure consequence."), BMW_RECALLS],
  },
  {
    slug: "f10m5-injectors", system: "Fuel", component: "S63TU fuel injectors", issue: "2013–2015 M5 fuel-injector coverage", aliases: ["S63T injectors", "misfire", "leaking injector"], severity: "critical", urgency: "watch", evidence: "BMW bulletin",
    description: "BMW extended injector coverage for eligible 2013–2015 F10 M5 production.", symptoms: "Cold-start misfire, fuel odor, rough running, mixture faults, smoke, or fuel dilution.", typicalMileage: "VIN and production specific; diagnosis is required.", preventativeAction: "Check fault and smooth-running data, oil for fuel dilution, and VIN-specific eligibility before replacing injectors.", appliesTo: { platforms: ["F10M5"], years: [2013, 2014, 2015], engines: ["S63TU"] },
    sources: [oem("S63T fuel-injector warranty extension", "BMW of North America · SIB 01 06 18", "https://static.nhtsa.gov/odi/tsbs/2018/MC-10138372-9999.pdf", "Official F10 M5 production range and component coverage.")],
  },
  {
    slug: "f10m5-oil-cooling-leaks", system: "Engine / turbo", issue: "Hot-V oil, coolant, and turbo-line leakage", aliases: ["S63 valley leak", "turbo coolant lines", "oil smoke"], severity: "critical", urgency: "watch", evidence: "Community consensus",
    description: "Dense hot-V plumbing, crankcase ventilation, covers, and turbo oil or coolant connections should be inspected as one system before a leak or smoke complaint is assigned to the turbochargers.", symptoms: "Burning odor, smoke after idle, coolant loss, oil in the valley or undertray, or turbo-area residue.", typicalMileage: "Heat-cycle, prior repair, and use dependent.", preventativeAction: "Pressure-test cooling loss, inspect from above and below, verify crankcase pressure, and trace the highest fresh leak.", appliesTo: platforms("F10M5"), sources: [community("F10 M5 technical forum", "Bimmerpost M5 community", "https://f10.m5post.com/forums/", "Owner and specialist diagnostic discussions for the S63TU platform." )],
  },
  {
    slug: "f10m5-rod-bearing-risk", system: "Engine", component: "Connecting-rod bearings", issue: "S63TU bearing and oil-pressure risk monitoring", aliases: ["M5 rod bearings", "S63 bearing knock"], severity: "critical", urgency: "watch", evidence: "Community consensus",
    description: "Modified output, sustained high load, oil condition, fuel dilution, and warm-up history influence bearing risk; there is no universal mileage diagnosis.", symptoms: "Metal in the filter, low oil pressure, knock, fuel-diluted oil, or unexplained internal-engine noise.", typicalMileage: "Condition, calibration, use, and service-history dependent.", preventativeAction: "Maintain correct oil level, avoid high load before full warm-up, inspect filter media, and obtain an S63-specialist diagnosis for noise or metal.", appliesTo: platforms("F10M5"), sources: [community("F10 M5 technical forum", "Bimmerpost M5 community", "https://f10.m5post.com/forums/", "Community evidence used as a monitoring prompt, not a failure prediction." )],
  },
  {
    slug: "f10m5-dct-leaks", system: "Transmission", issue: "M-DCT leakage, clutch adaptation, and shift faults", aliases: ["DCT pan leak", "clutch adaptation", "transmission malfunction"], severity: "critical", urgency: "watch", evidence: "Community consensus",
    description: "Leaks, low fluid, temperature, adaptation, electrical faults, or clutch wear can create overlapping M-DCT complaints.", symptoms: "Transmission warning, delayed engagement, harsh or slipping shifts, fluid under the gearbox, or clutch-temperature warnings.", typicalMileage: "Use, heat, service, and seal condition dependent.", preventativeAction: "Scan the DCT, locate leakage, verify fluid level by the correct temperature procedure, and review adaptations before replacing clutch or mechatronic assemblies.", appliesTo: { platforms: ["F10M5"], transmissions: ["7-speed M-DCT"] }, sources: [community("F10 M5 technical forum", "Bimmerpost M5 community", "https://f10.m5post.com/forums/", "Owner and specialist transmission-diagnostic discussions." )],
  },
];

// REVIEW DECISION: community-backed patterns stay explicitly labeled and every safety campaign instructs the owner to verify the VIN.
