import {
  ENHANCED_INSIGHTS,
  ENHANCED_ISSUES,
  ENHANCED_PLATFORMS,
  ENHANCED_SCHEDULE_PROFILES,
  ENHANCED_SCHEDULE_ROWS,
  ENHANCED_SCHEDULES,
  ENHANCED_VARIANTS,
} from "./enhancedVehicleData";
import {
  SKYLINE_INSIGHTS,
  SKYLINE_ISSUES,
  SKYLINE_PLATFORMS,
  SKYLINE_SCHEDULE_PROFILES,
  SKYLINE_SCHEDULE_ROWS,
  SKYLINE_SCHEDULES,
  SKYLINE_VARIANTS,
} from "./skylineVehicleData";
import {
  COMMUNITY_WORKBOOK_INSIGHTS,
  COMMUNITY_WORKBOOK_ISSUES,
  COMMUNITY_WORKBOOK_PLATFORMS,
  COMMUNITY_WORKBOOK_SCHEDULE_PROFILES,
  COMMUNITY_WORKBOOK_SCHEDULE_ROWS,
  COMMUNITY_WORKBOOK_SCHEDULES,
  COMMUNITY_WORKBOOK_VARIANTS,
} from "./communityWorkbookVehicleData";
import {
  SECOND_GEN_TWIN_INSIGHTS,
  SECOND_GEN_TWIN_ISSUES,
  SECOND_GEN_TWIN_PLATFORMS,
  SECOND_GEN_TWIN_SCHEDULE_PROFILES,
  SECOND_GEN_TWIN_SCHEDULE_ROWS,
  SECOND_GEN_TWIN_SCHEDULES,
  SECOND_GEN_TWIN_VARIANTS,
} from "./secondGenTwinsVehicleData";
import {
  SUBARU_BRZ_INSIGHTS,
  SUBARU_BRZ_ISSUES,
  SUBARU_BRZ_PLATFORMS,
  SUBARU_BRZ_SCHEDULE_PROFILES,
  SUBARU_BRZ_SCHEDULE_ROWS,
  SUBARU_BRZ_SCHEDULES,
  SUBARU_BRZ_VARIANTS,
} from "./subaruBrzCatalogData";

// The live catalog already includes a combined BRZ/GR86 import. Keep its Toyota
// data while the attached Subaru workbook supplies the more precise BRZ trims.
const TOYOTA_TWIN_PLATFORMS = SECOND_GEN_TWIN_PLATFORMS.filter((platform) => platform.value === "ZN8");
const TOYOTA_TWIN_VARIANTS = SECOND_GEN_TWIN_VARIANTS.filter((variant) => variant.platform === "ZN8");
const TOYOTA_TWIN_SCHEDULE_PROFILES = SECOND_GEN_TWIN_SCHEDULE_PROFILES.filter((profile) => profile.platform === "ZN8");
const TOYOTA_TWIN_SCHEDULE_ROWS = Object.fromEntries(Object.entries(SECOND_GEN_TWIN_SCHEDULE_ROWS)
  .filter(([rowId]) => rowId.startsWith("research-zn8-")));
const TOYOTA_TWIN_SCHEDULES = Object.fromEntries(Object.entries(SECOND_GEN_TWIN_SCHEDULES)
  .filter(([scheduleId]) => scheduleId.startsWith("research-zn8-")));
const TOYOTA_TWIN_ISSUES = SECOND_GEN_TWIN_ISSUES.filter((issue) => issue.platform === "ZN8");
const TOYOTA_TWIN_INSIGHTS = SECOND_GEN_TWIN_INSIGHTS.filter((insight) => insight.platform === "ZN8");

// One adapter keeps every workbook-backed dataset on the same catalog path.
// Existing identifiers remain unchanged while new imports add their own stable IDs.
export const RESEARCH_PLATFORMS = [...ENHANCED_PLATFORMS, ...SKYLINE_PLATFORMS, ...COMMUNITY_WORKBOOK_PLATFORMS, ...TOYOTA_TWIN_PLATFORMS, ...SUBARU_BRZ_PLATFORMS];
export const RESEARCH_VARIANTS = [...ENHANCED_VARIANTS, ...SKYLINE_VARIANTS, ...COMMUNITY_WORKBOOK_VARIANTS, ...TOYOTA_TWIN_VARIANTS, ...SUBARU_BRZ_VARIANTS];
export const RESEARCH_SCHEDULE_PROFILES = [...ENHANCED_SCHEDULE_PROFILES, ...SKYLINE_SCHEDULE_PROFILES, ...COMMUNITY_WORKBOOK_SCHEDULE_PROFILES, ...TOYOTA_TWIN_SCHEDULE_PROFILES, ...SUBARU_BRZ_SCHEDULE_PROFILES];
export const RESEARCH_SCHEDULE_ROWS = { ...ENHANCED_SCHEDULE_ROWS, ...SKYLINE_SCHEDULE_ROWS, ...COMMUNITY_WORKBOOK_SCHEDULE_ROWS, ...TOYOTA_TWIN_SCHEDULE_ROWS, ...SUBARU_BRZ_SCHEDULE_ROWS };
export const RESEARCH_SCHEDULES = { ...ENHANCED_SCHEDULES, ...SKYLINE_SCHEDULES, ...COMMUNITY_WORKBOOK_SCHEDULES, ...TOYOTA_TWIN_SCHEDULES, ...SUBARU_BRZ_SCHEDULES };
export const RESEARCH_ISSUES = [...ENHANCED_ISSUES, ...SKYLINE_ISSUES, ...COMMUNITY_WORKBOOK_ISSUES, ...TOYOTA_TWIN_ISSUES, ...SUBARU_BRZ_ISSUES];
export const RESEARCH_INSIGHTS = [...ENHANCED_INSIGHTS, ...SKYLINE_INSIGHTS, ...COMMUNITY_WORKBOOK_INSIGHTS, ...TOYOTA_TWIN_INSIGHTS, ...SUBARU_BRZ_INSIGHTS];
