import {
  ENHANCED_INSIGHTS,
  ENHANCED_ISSUES,
  ENHANCED_PLATFORMS,
  ENHANCED_SCHEDULE_PROFILES,
  ENHANCED_SCHEDULE_ROWS,
  ENHANCED_SCHEDULES,
  ENHANCED_VARIANTS,
} from "./enhancedVehicleData";
import {
  SKYLINE_INSIGHTS,
  SKYLINE_ISSUES,
  SKYLINE_PLATFORMS,
  SKYLINE_SCHEDULE_PROFILES,
  SKYLINE_SCHEDULE_ROWS,
  SKYLINE_SCHEDULES,
  SKYLINE_VARIANTS,
} from "./skylineVehicleData";
import {
  COMMUNITY_WORKBOOK_INSIGHTS,
  COMMUNITY_WORKBOOK_ISSUES,
  COMMUNITY_WORKBOOK_PLATFORMS,
  COMMUNITY_WORKBOOK_SCHEDULE_PROFILES,
  COMMUNITY_WORKBOOK_SCHEDULE_ROWS,
  COMMUNITY_WORKBOOK_SCHEDULES,
  COMMUNITY_WORKBOOK_VARIANTS,
} from "./communityWorkbookVehicleData";
import {
  SECOND_GEN_TWIN_INSIGHTS,
  SECOND_GEN_TWIN_ISSUES,
  SECOND_GEN_TWIN_PLATFORMS,
  SECOND_GEN_TWIN_SCHEDULE_PROFILES,
  SECOND_GEN_TWIN_SCHEDULE_ROWS,
  SECOND_GEN_TWIN_SCHEDULES,
  SECOND_GEN_TWIN_VARIANTS,
} from "./secondGenTwinsVehicleData";

// One adapter keeps every workbook-backed dataset on the same catalog path.
// Existing identifiers remain unchanged while new imports add their own stable IDs.
export const RESEARCH_PLATFORMS = [...ENHANCED_PLATFORMS, ...SKYLINE_PLATFORMS, ...COMMUNITY_WORKBOOK_PLATFORMS, ...SECOND_GEN_TWIN_PLATFORMS];
export const RESEARCH_VARIANTS = [...ENHANCED_VARIANTS, ...SKYLINE_VARIANTS, ...COMMUNITY_WORKBOOK_VARIANTS, ...SECOND_GEN_TWIN_VARIANTS];
export const RESEARCH_SCHEDULE_PROFILES = [...ENHANCED_SCHEDULE_PROFILES, ...SKYLINE_SCHEDULE_PROFILES, ...COMMUNITY_WORKBOOK_SCHEDULE_PROFILES, ...SECOND_GEN_TWIN_SCHEDULE_PROFILES];
export const RESEARCH_SCHEDULE_ROWS = { ...ENHANCED_SCHEDULE_ROWS, ...SKYLINE_SCHEDULE_ROWS, ...COMMUNITY_WORKBOOK_SCHEDULE_ROWS, ...SECOND_GEN_TWIN_SCHEDULE_ROWS };
export const RESEARCH_SCHEDULES = { ...ENHANCED_SCHEDULES, ...SKYLINE_SCHEDULES, ...COMMUNITY_WORKBOOK_SCHEDULES, ...SECOND_GEN_TWIN_SCHEDULES };
export const RESEARCH_ISSUES = [...ENHANCED_ISSUES, ...SKYLINE_ISSUES, ...COMMUNITY_WORKBOOK_ISSUES, ...SECOND_GEN_TWIN_ISSUES];
export const RESEARCH_INSIGHTS = [...ENHANCED_INSIGHTS, ...SKYLINE_INSIGHTS, ...COMMUNITY_WORKBOOK_INSIGHTS, ...SECOND_GEN_TWIN_INSIGHTS];
