// Generated from the user-provided Subaru ZD8 BRZ maintenance workbook.
// Stable ZC6 identifiers remain in enhancedVehicleData.ts; this module adds ZD8 without rewriting saved vehicles.

import type { EnhancedInsightRecord, EnhancedIssueRecord, EnhancedPlatformRecord, EnhancedScheduleProfileRecord, EnhancedScheduleRow, EnhancedVariantRecord } from "./enhancedVehicleData";

export const SUBARU_BRZ_PLATFORMS: EnhancedPlatformRecord[] = [
  {
    "value": "ZD8",
    "brand": "Subaru",
    "label": "BRZ (second generation ZD8)",
    "yearStart": 2022,
    "yearEnd": 2026
  }
];

export const SUBARU_BRZ_VARIANTS: EnhancedVariantRecord[] = [
  {
    "brand": "Subaru",
    "platform": "ZD8",
    "scheduleId": "research-zd8-brz-22-23-6mt",
    "tab": "BRZ 22-23 6MT",
    "trim": "Standard",
    "label": "Standard",
    "yearStart": 2022,
    "yearEnd": 2023,
    "engineCodes": [
      "FA24D"
    ],
    "engineLabel": "FA24D / FA24 2.4L naturally aspirated flat-four",
    "drivetrain": "RWD",
    "transmission": "6-speed manual",
    "body": "Coupe",
    "applicability": "2022–2023 Subaru BRZ (ZD8), 6-speed manual; verify exact trim, model year, and VIN.",
    "sourceWorkbook": "Subaru ZD8 BRZ USDM Maintenance Schedules - Community Revised E46 Standard (2).xlsx",
    "engineCode": "FA24D"
  },
  {
    "brand": "Subaru",
    "platform": "ZD8",
    "scheduleId": "research-zd8-brz-22-23-6at",
    "tab": "BRZ 22-23 6AT",
    "trim": "Standard",
    "label": "Standard",
    "yearStart": 2022,
    "yearEnd": 2023,
    "engineCodes": [
      "FA24D"
    ],
    "engineLabel": "FA24D / FA24 2.4L naturally aspirated flat-four",
    "drivetrain": "RWD",
    "transmission": "6-speed automatic",
    "body": "Coupe",
    "applicability": "2022–2023 Subaru BRZ (ZD8), 6-speed automatic; verify exact trim, model year, and VIN.",
    "sourceWorkbook": "Subaru ZD8 BRZ USDM Maintenance Schedules - Community Revised E46 Standard (2).xlsx",
    "engineCode": "FA24D"
  },
  {
    "brand": "Subaru",
    "platform": "ZD8",
    "scheduleId": "research-zd8-brz-24-26-6mt",
    "tab": "BRZ 24-26 6MT",
    "trim": "Standard",
    "label": "Standard",
    "yearStart": 2024,
    "yearEnd": 2026,
    "engineCodes": [
      "FA24D"
    ],
    "engineLabel": "FA24D / FA24 2.4L naturally aspirated flat-four",
    "drivetrain": "RWD",
    "transmission": "6-speed manual",
    "body": "Coupe",
    "applicability": "2024–2026 Subaru BRZ (ZD8), 6-speed manual; verify exact trim, model year, and VIN.",
    "sourceWorkbook": "Subaru ZD8 BRZ USDM Maintenance Schedules - Community Revised E46 Standard (2).xlsx",
    "engineCode": "FA24D"
  },
  {
    "brand": "Subaru",
    "platform": "ZD8",
    "scheduleId": "research-zd8-brz-24-26-6mt",
    "tab": "BRZ 24-26 6MT",
    "trim": "Series.Purple",
    "label": "Series.Purple",
    "yearStart": 2025,
    "yearEnd": 2025,
    "engineCodes": [
      "FA24D"
    ],
    "engineLabel": "FA24D / FA24 2.4L naturally aspirated flat-four",
    "drivetrain": "RWD",
    "transmission": "6-speed manual",
    "body": "Coupe",
    "applicability": "2024–2026 Subaru BRZ (ZD8), 6-speed manual; verify exact trim, model year, and VIN.",
    "sourceWorkbook": "Subaru ZD8 BRZ USDM Maintenance Schedules - Community Revised E46 Standard (2).xlsx",
    "engineCode": "FA24D"
  },
  {
    "brand": "Subaru",
    "platform": "ZD8",
    "scheduleId": "research-zd8-brz-24-26-6at",
    "tab": "BRZ 24-26 6AT",
    "trim": "Standard",
    "label": "Standard",
    "yearStart": 2024,
    "yearEnd": 2026,
    "engineCodes": [
      "FA24D"
    ],
    "engineLabel": "FA24D / FA24 2.4L naturally aspirated flat-four",
    "drivetrain": "RWD",
    "transmission": "6-speed automatic",
    "body": "Coupe",
    "applicability": "2024–2026 Subaru BRZ (ZD8), 6-speed automatic; verify exact trim, model year, and VIN.",
    "sourceWorkbook": "Subaru ZD8 BRZ USDM Maintenance Schedules - Community Revised E46 Standard (2).xlsx",
    "engineCode": "FA24D"
  },
  {
    "brand": "Subaru",
    "platform": "ZD8",
    "scheduleId": "research-zd8-brz-ts-24-26-6mt",
    "tab": "BRZ tS 24-26 6MT",
    "trim": "tS",
    "label": "tS",
    "yearStart": 2024,
    "yearEnd": 2026,
    "engineCodes": [
      "FA24D"
    ],
    "engineLabel": "FA24D / FA24 2.4L naturally aspirated flat-four",
    "drivetrain": "RWD",
    "transmission": "6-speed manual",
    "body": "Coupe",
    "applicability": "2024–2026 Subaru BRZ (ZD8), 6-speed manual; verify exact trim, model year, and VIN.",
    "sourceWorkbook": "Subaru ZD8 BRZ USDM Maintenance Schedules - Community Revised E46 Standard (2).xlsx",
    "engineCode": "FA24D"
  },
  {
    "brand": "Subaru",
    "platform": "ZD8",
    "scheduleId": "research-zd8-brz-ts-24-26-6mt",
    "tab": "BRZ tS 24-26 6MT",
    "trim": "Series.Yellow",
    "label": "Series.Yellow",
    "yearStart": 2026,
    "yearEnd": 2026,
    "engineCodes": [
      "FA24D"
    ],
    "engineLabel": "FA24D / FA24 2.4L naturally aspirated flat-four",
    "drivetrain": "RWD",
    "transmission": "6-speed manual",
    "body": "Coupe",
    "applicability": "2024–2026 Subaru BRZ (ZD8), 6-speed manual; verify exact trim, model year, and VIN.",
    "sourceWorkbook": "Subaru ZD8 BRZ USDM Maintenance Schedules - Community Revised E46 Standard (2).xlsx",
    "engineCode": "FA24D"
  }
];

export const SUBARU_BRZ_SCHEDULE_PROFILES: EnhancedScheduleProfileRecord[] = [
  {
    "brand": "Subaru",
    "platform": "ZD8",
    "scheduleId": "research-zd8-brz-22-23-6mt",
    "tab": "BRZ 22-23 6MT",
    "trim": "Standard",
    "label": "Standard",
    "yearStart": 2022,
    "yearEnd": 2023,
    "engineCodes": [
      "FA24D"
    ],
    "engineLabel": "FA24D / FA24 2.4L naturally aspirated flat-four",
    "drivetrain": "RWD",
    "transmission": "6-speed manual",
    "body": "Coupe",
    "applicability": "2022–2023 Subaru BRZ (ZD8), 6-speed manual; verify exact trim, model year, and VIN.",
    "sourceWorkbook": "Subaru ZD8 BRZ USDM Maintenance Schedules - Community Revised E46 Standard (2).xlsx"
  },
  {
    "brand": "Subaru",
    "platform": "ZD8",
    "scheduleId": "research-zd8-brz-22-23-6at",
    "tab": "BRZ 22-23 6AT",
    "trim": "Standard",
    "label": "Standard",
    "yearStart": 2022,
    "yearEnd": 2023,
    "engineCodes": [
      "FA24D"
    ],
    "engineLabel": "FA24D / FA24 2.4L naturally aspirated flat-four",
    "drivetrain": "RWD",
    "transmission": "6-speed automatic",
    "body": "Coupe",
    "applicability": "2022–2023 Subaru BRZ (ZD8), 6-speed automatic; verify exact trim, model year, and VIN.",
    "sourceWorkbook": "Subaru ZD8 BRZ USDM Maintenance Schedules - Community Revised E46 Standard (2).xlsx"
  },
  {
    "brand": "Subaru",
    "platform": "ZD8",
    "scheduleId": "research-zd8-brz-24-26-6mt",
    "tab": "BRZ 24-26 6MT",
    "trim": "Standard / Series.Purple",
    "label": "Standard / Series.Purple",
    "yearStart": 2024,
    "yearEnd": 2026,
    "engineCodes": [
      "FA24D"
    ],
    "engineLabel": "FA24D / FA24 2.4L naturally aspirated flat-four",
    "drivetrain": "RWD",
    "transmission": "6-speed manual",
    "body": "Coupe",
    "applicability": "2024–2026 Subaru BRZ (ZD8), 6-speed manual; verify exact trim, model year, and VIN.",
    "sourceWorkbook": "Subaru ZD8 BRZ USDM Maintenance Schedules - Community Revised E46 Standard (2).xlsx"
  },
  {
    "brand": "Subaru",
    "platform": "ZD8",
    "scheduleId": "research-zd8-brz-24-26-6at",
    "tab": "BRZ 24-26 6AT",
    "trim": "Standard",
    "label": "Standard",
    "yearStart": 2024,
    "yearEnd": 2026,
    "engineCodes": [
      "FA24D"
    ],
    "engineLabel": "FA24D / FA24 2.4L naturally aspirated flat-four",
    "drivetrain": "RWD",
    "transmission": "6-speed automatic",
    "body": "Coupe",
    "applicability": "2024–2026 Subaru BRZ (ZD8), 6-speed automatic; verify exact trim, model year, and VIN.",
    "sourceWorkbook": "Subaru ZD8 BRZ USDM Maintenance Schedules - Community Revised E46 Standard (2).xlsx"
  },
  {
    "brand": "Subaru",
    "platform": "ZD8",
    "scheduleId": "research-zd8-brz-ts-24-26-6mt",
    "tab": "BRZ tS 24-26 6MT",
    "trim": "tS / Series.Yellow",
    "label": "tS / Series.Yellow",
    "yearStart": 2024,
    "yearEnd": 2026,
    "engineCodes": [
      "FA24D"
    ],
    "engineLabel": "FA24D / FA24 2.4L naturally aspirated flat-four",
    "drivetrain": "RWD",
    "transmission": "6-speed manual",
    "body": "Coupe",
    "applicability": "2024–2026 Subaru BRZ (ZD8), 6-speed manual; verify exact trim, model year, and VIN.",
    "sourceWorkbook": "Subaru ZD8 BRZ USDM Maintenance Schedules - Community Revised E46 Standard (2).xlsx"
  }
];

export const SUBARU_BRZ_SCHEDULE_ROWS: Record<string, EnhancedScheduleRow> = {
  "zd8-engine-oil-and-filter-55c2db0122": {
    "name": "Engine oil & filter",
    "category": "Engine",
    "severity": "important",
    "entryType": "OEM Scheduled / Track overlay",
    "action": "Replace",
    "mileage": 6000,
    "months": 6,
    "trigger": "Normal factory cadence. Severe short-trip/extreme-condition oil cadence: about 3,000 mi / 3 mo.",
    "basis": "Subaru OEM + track/severe-use overlay",
    "amount": "5.3 US qt / 5.0 L with filter; 0W-20 factory fill",
    "specification": "",
    "primaryUrl": "https://techinfo.subaru.com/stis/doc/warrantyBooklet/2022_war_and_maint_120721.PDF",
    "secondaryUrl": "https://techinfo.subaru.com/stis/doc/ownerManual/MSA5B2606A_STIS.pdf",
    "verification": "OEM normal interval",
    "notes": "Do not present a track oil strategy as the street factory requirement."
  },
  "zd8-brake-fluid-clutch-fluid-7e8b3c8032": {
    "name": "Brake fluid / clutch fluid",
    "category": "Brakes & safety",
    "severity": "important",
    "entryType": "OEM Scheduled / Severe-use",
    "action": "Replace",
    "mileage": 30000,
    "months": 30,
    "trigger": "Normal replacement around 30k; high-humidity/mountain or repeated track use warrants shorter service. Manual cars share brake/clutch fluid circuit requirements.",
    "basis": "Subaru OEM + severe-use",
    "amount": "~1 L service quantity",
    "specification": "",
    "primaryUrl": "https://techinfo.subaru.com/stis/doc/warrantyBooklet/2022_war_and_maint_120721.PDF",
    "secondaryUrl": "https://techinfo.subaru.com/stis/doc/ownerManual/MSA5B2606A_STIS.pdf",
    "verification": "OEM schedule / severe note",
    "notes": "Subaru severe-service guidance shortens brake/clutch-fluid service under specified conditions such as high humidity/mountain use; track heat may justify event-based service."
  },
  "zd8-engine-air-filter-a2457a35ad": {
    "name": "Engine air filter",
    "category": "Filters & climate",
    "severity": "routine",
    "entryType": "OEM Scheduled",
    "action": "Replace / inspect",
    "mileage": 30000,
    "months": 30,
    "trigger": "Factory schedule; replace sooner in dust.",
    "basis": "Subaru OEM",
    "amount": "1 element",
    "specification": "",
    "primaryUrl": "https://techinfo.subaru.com/stis/doc/warrantyBooklet/2022_war_and_maint_120721.PDF",
    "secondaryUrl": "https://techinfo.subaru.com/stis/doc/ownerManual/MSA5B2606A_STIS.pdf",
    "verification": "OEM",
    "notes": "No performance filter is required for normal maintenance."
  },
  "zd8-cabin-microfilter-bf52b67755": {
    "name": "Cabin microfilter",
    "category": "Filters & climate",
    "severity": "routine",
    "entryType": "OEM Scheduled",
    "action": "Replace",
    "mileage": 12000,
    "months": 12,
    "trigger": "Factory HVAC-filter interval; dust/heavy traffic can shorten life.",
    "basis": "Subaru OEM",
    "amount": "1 cabin filter",
    "specification": "",
    "primaryUrl": "https://techinfo.subaru.com/stis/doc/warrantyBooklet/2022_war_and_maint_120721.PDF",
    "secondaryUrl": "https://techinfo.subaru.com/stis/doc/ownerManual/MSA5B2606A_STIS.pdf",
    "verification": "OEM",
    "notes": "Brand schedules differ; this is intentionally not standardized."
  },
  "zd8-fuel-filter-8fce89d084": {
    "name": "Fuel filter",
    "category": "Engine",
    "severity": "important",
    "entryType": "OEM / Condition",
    "action": "Inspect / replace per factory schedule or contamination",
    "mileage": 72000,
    "months": null,
    "trigger": "Subaru schedule replaces the fuel filter at 72,000 miles; fuel contamination or pressure faults can justify earlier diagnosis.",
    "basis": "Subaru OEM / condition",
    "amount": "In-tank / system-specific",
    "specification": "",
    "primaryUrl": "https://techinfo.subaru.com/stis/doc/warrantyBooklet/2022_war_and_maint_120721.PDF",
    "secondaryUrl": "https://techinfo.subaru.com/stis/doc/ownerManual/MSA5B2606A_STIS.pdf",
    "verification": "Brand-specific",
    "notes": "Fuel filter is a scheduled Subaru item; use fuel-pressure/contamination diagnosis if symptoms occur."
  },
  "zd8-manual-transmission-fluid-8e6a738a87": {
    "name": "Manual transmission fluid",
    "category": "Driveline",
    "severity": "important",
    "entryType": "Transmission-specific",
    "action": "Inspect / preventive replace",
    "mileage": 24000,
    "months": 24,
    "trigger": "Subaru BRZ schedule periodically inspects manual-transmission gear oil; severe use can require more frequent replacement. The 24,000-mile tracker point is an inspection cadence.",
    "basis": "Subaru OEM inspection + severe-use / preventive",
    "amount": "2.3 US qt / 2.2 L; low-viscosity manual transmission gear oil, verify MY spec",
    "specification": "",
    "primaryUrl": "https://techinfo.subaru.com/stis/doc/warrantyBooklet/2022_war_and_maint_120721.PDF",
    "secondaryUrl": "https://techinfo.subaru.com/stis/doc/ownerManual/MSA5B2606A_STIS.pdf",
    "verification": "Transmission-specific",
    "notes": "Do not interpret 24,000 miles as a blanket Subaru normal-service fluid replacement interval."
  },
  "zd8-rear-differential-fluid-68e307ffd9": {
    "name": "Rear differential fluid",
    "category": "Driveline",
    "severity": "important",
    "entryType": "OEM Inspection / Preventive",
    "action": "Inspect / replace",
    "mileage": 60000,
    "months": 48,
    "trigger": "Subaru BRZ schedule replaces rear differential gear oil every 60,000 miles or 4 years; severe-use conditions can require shorter service.",
    "basis": "Subaru OEM",
    "amount": "1.22 US qt / 1.15 L; GL-5 75W-85/75W-90 per manual",
    "specification": "",
    "primaryUrl": "https://techinfo.subaru.com/stis/doc/warrantyBooklet/2022_war_and_maint_120721.PDF",
    "secondaryUrl": "https://techinfo.subaru.com/stis/doc/ownerManual/MSA5B2606A_STIS.pdf",
    "verification": "Brand-specific",
    "notes": "The 60,000-mile / 4-year rear-differential replacement is a Subaru factory schedule item; track/drift use may justify shorter service."
  },
  "zd8-spark-plugs-610ca02db3": {
    "name": "Spark plugs",
    "category": "Engine",
    "severity": "important",
    "entryType": "OEM Scheduled",
    "action": "Replace",
    "mileage": 60000,
    "months": 60,
    "trigger": "Factory schedule.",
    "basis": "Subaru OEM",
    "amount": "4 iridium plugs",
    "specification": "",
    "primaryUrl": "https://techinfo.subaru.com/stis/doc/warrantyBooklet/2022_war_and_maint_120721.PDF",
    "secondaryUrl": "https://techinfo.subaru.com/stis/doc/ownerManual/MSA5B2606A_STIS.pdf",
    "verification": "OEM",
    "notes": "Misfire under track load also warrants coil/fueling diagnosis."
  },
  "zd8-oxygen-a-f-sensors-dddb6bf98e": {
    "name": "Oxygen / A/F sensors",
    "category": "Electrical",
    "severity": "important",
    "entryType": "Condition-based",
    "action": "Diagnose / replace",
    "mileage": null,
    "months": null,
    "trigger": "MIL, fuel-trim, catalyst/readiness or sensor faults.",
    "basis": "Condition-based",
    "amount": "As equipped",
    "specification": "",
    "primaryUrl": "https://techinfo.subaru.com/stis/doc/ownerManual/MSA5B2606A_STIS.pdf",
    "secondaryUrl": "https://techinfo.subaru.com/stis/doc/warrantyBooklet/2022_war_and_maint_120721.PDF",
    "verification": "Condition-based",
    "notes": "No fixed mileage replacement interval."
  },
  "zd8-accessory-serpentine-belt-8afb76d17d": {
    "name": "Accessory / serpentine belt",
    "category": "Engine",
    "severity": "important",
    "entryType": "OEM Inspection",
    "action": "Inspect / replace by condition",
    "mileage": 30000,
    "months": 30,
    "trigger": "Inspect at factory periodic service; replace for cracks, glazing, contamination or damage.",
    "basis": "OEM inspection",
    "amount": "1 accessory belt",
    "specification": "",
    "primaryUrl": "https://techinfo.subaru.com/stis/doc/warrantyBooklet/2022_war_and_maint_120721.PDF",
    "secondaryUrl": "https://techinfo.subaru.com/stis/doc/ownerManual/MSA5B2606A_STIS.pdf",
    "verification": "Inspection",
    "notes": "Chain-driven engine; this is not a timing belt."
  },
  "zd8-belt-tensioner-and-idler-pulleys-9671971eb4": {
    "name": "Belt tensioner & idler pulleys",
    "category": "Engine",
    "severity": "important",
    "entryType": "Condition-based",
    "action": "Inspect bearings / tension",
    "mileage": 60000,
    "months": 60,
    "trigger": "Noise, belt tracking, belt service.",
    "basis": "Preventive inspection",
    "amount": "As equipped",
    "specification": "",
    "primaryUrl": "https://techinfo.subaru.com/stis/doc/ownerManual/MSA5B2606A_STIS.pdf",
    "secondaryUrl": "https://www.ft86club.com/forums/",
    "verification": "Condition-based",
    "notes": "No fixed OEM replacement interval asserted."
  },
  "zd8-engine-coolant-8de365ca94": {
    "name": "Engine coolant",
    "category": "Cooling",
    "severity": "routine",
    "entryType": "OEM Scheduled",
    "action": "Replace",
    "mileage": 137500,
    "months": 132,
    "trigger": "First replacement at 132 months; then 75,000 mi / 72 months thereafter.",
    "basis": "Subaru OEM",
    "amount": "Verify exact total system capacity",
    "specification": "",
    "primaryUrl": "https://techinfo.subaru.com/stis/doc/warrantyBooklet/2022_war_and_maint_120721.PDF",
    "secondaryUrl": "https://techinfo.subaru.com/stis/doc/ownerManual/MSA5B2606A_STIS.pdf",
    "verification": "OEM",
    "notes": "Toyota lists 135k first replacement; Subaru lists 137.5k first replacement."
  },
  "zd8-electric-power-steering-713d7c8d5b": {
    "name": "Electric power steering",
    "category": "Chassis",
    "severity": "important",
    "entryType": "Architecture / Inspection",
    "action": "No hydraulic fluid; inspect EPS",
    "mileage": null,
    "months": null,
    "trigger": "Steering warning, alignment/suspension work, abnormal assist.",
    "basis": "Architecture",
    "amount": "N/A",
    "specification": "",
    "primaryUrl": "https://techinfo.subaru.com/stis/doc/ownerManual/MSA5B2606A_STIS.pdf",
    "secondaryUrl": "https://techinfo.subaru.com/stis/doc/warrantyBooklet/2022_war_and_maint_120721.PDF",
    "verification": "Architecture",
    "notes": "Core power-steering-fluid category adapted to EPS."
  },
  "zd8-water-pump-e282bdb6e0": {
    "name": "Water pump",
    "category": "Cooling",
    "severity": "important",
    "entryType": "Condition-based",
    "action": "Inspect / replace as needed",
    "mileage": null,
    "months": null,
    "trigger": "Coolant leak, bearing noise, temperature-control fault or engine service.",
    "basis": "Condition-based",
    "amount": "1 pump",
    "specification": "",
    "primaryUrl": "https://techinfo.subaru.com/stis/doc/ownerManual/MSA5B2606A_STIS.pdf",
    "secondaryUrl": "https://www.ft86club.com/forums/",
    "verification": "Condition-based",
    "notes": "Timing chain does not create a timing-belt-style pump interval."
  },
  "zd8-thermostat-c127aeaa73": {
    "name": "Thermostat",
    "category": "Cooling",
    "severity": "important",
    "entryType": "Condition-based",
    "action": "Diagnose / replace",
    "mileage": null,
    "months": null,
    "trigger": "Slow warm-up, overheating, temperature-control fault.",
    "basis": "Condition-based",
    "amount": "1 thermostat",
    "specification": "",
    "primaryUrl": "https://techinfo.subaru.com/stis/doc/ownerManual/MSA5B2606A_STIS.pdf",
    "secondaryUrl": "https://www.ft86club.com/forums/",
    "verification": "Condition-based",
    "notes": "No low-temp thermostat recommendation for normal street use."
  },
  "zd8-thermostat-housing-coolant-necks-1fba6746f0": {
    "name": "Thermostat housing / coolant necks",
    "category": "Cooling",
    "severity": "important",
    "entryType": "Inspection",
    "action": "Inspect seals / housings",
    "mileage": null,
    "months": 24,
    "trigger": "Cooling service or seepage.",
    "basis": "Condition-based",
    "amount": "As required",
    "specification": "",
    "primaryUrl": "https://techinfo.subaru.com/stis/doc/ownerManual/MSA5B2606A_STIS.pdf",
    "secondaryUrl": "https://www.ft86club.com/forums/",
    "verification": "Condition-based",
    "notes": "No platform-wide fixed failure interval."
  },
  "zd8-radiator-condenser-cooling-stack-dd3e0cb9dc": {
    "name": "Radiator / condenser cooling stack",
    "category": "Cooling",
    "severity": "important",
    "entryType": "Inspection",
    "action": "Inspect / clean / pressure-test",
    "mileage": null,
    "months": 12,
    "trigger": "Track debris, impact, overheating, coolant leak.",
    "basis": "Condition + severe-use",
    "amount": "As required",
    "specification": "",
    "primaryUrl": "https://techinfo.subaru.com/stis/doc/ownerManual/MSA5B2606A_STIS.pdf",
    "secondaryUrl": "https://www.ft86club.com/forums/",
    "verification": "Condition-based",
    "notes": "Track rubber/debris can obstruct cooling stack."
  },
  "zd8-coolant-reservoir-cap-18c5b8ef63": {
    "name": "Coolant reservoir / cap",
    "category": "Cooling",
    "severity": "important",
    "entryType": "Inspection",
    "action": "Inspect / replace by condition",
    "mileage": null,
    "months": 12,
    "trigger": "Coolant loss, cracks, cap-seal issue.",
    "basis": "Condition-based",
    "amount": "As equipped",
    "specification": "",
    "primaryUrl": "https://techinfo.subaru.com/stis/doc/ownerManual/MSA5B2606A_STIS.pdf",
    "secondaryUrl": "https://www.ft86club.com/forums/",
    "verification": "Condition-based",
    "notes": "Do not repeatedly top off without finding the leak."
  },
  "zd8-electric-cooling-fans-84ac6ac13a": {
    "name": "Electric cooling fans",
    "category": "Cooling",
    "severity": "important",
    "entryType": "Architecture / Inspection",
    "action": "Function-test",
    "mileage": null,
    "months": 12,
    "trigger": "A/C performance, idle temperature, fan fault.",
    "basis": "Architecture / condition",
    "amount": "Electric fans",
    "specification": "",
    "primaryUrl": "https://techinfo.subaru.com/stis/doc/ownerManual/MSA5B2606A_STIS.pdf",
    "secondaryUrl": "https://www.ft86club.com/forums/",
    "verification": "Condition-based",
    "notes": "Core mechanical-fan category adapted to electric fans."
  },
  "zd8-coolant-fuel-and-evap-hoses-cd711f74f5": {
    "name": "Coolant, fuel & EVAP hoses",
    "category": "Cooling",
    "severity": "important",
    "entryType": "Inspection",
    "action": "Inspect",
    "mileage": 30000,
    "months": 30,
    "trigger": "Leaks, damage, fuel odor, track heat.",
    "basis": "OEM inspection + age",
    "amount": "As required",
    "specification": "",
    "primaryUrl": "https://techinfo.subaru.com/stis/doc/warrantyBooklet/2022_war_and_maint_120721.PDF",
    "secondaryUrl": "https://techinfo.subaru.com/stis/doc/ownerManual/MSA5B2606A_STIS.pdf",
    "verification": "Inspection",
    "notes": "Fuel system is high-pressure direct + port injection; depressurize using correct procedure."
  },
  "zd8-intake-ducts-vacuum-lines-and-pcv-4ee304c8fc": {
    "name": "Intake ducts, vacuum lines & PCV",
    "category": "Engine",
    "severity": "important",
    "entryType": "Inspection",
    "action": "Inspect / smoke-test",
    "mileage": 30000,
    "months": 30,
    "trigger": "Fuel trim, idle issue, oil mist, post-MAF leak.",
    "basis": "Preventive inspection",
    "amount": "As required",
    "specification": "",
    "primaryUrl": "https://techinfo.subaru.com/stis/doc/ownerManual/MSA5B2606A_STIS.pdf",
    "secondaryUrl": "https://www.ft86club.com/forums/",
    "verification": "Condition-based",
    "notes": "D-4S port injection reduces—but does not eliminate—intake-deposit concerns."
  },
  "zd8-chassis-bushings-ball-joints-and-wheel-bearings-905e89122a": {
    "name": "Chassis, bushings, ball joints & wheel bearings",
    "category": "Chassis",
    "severity": "critical",
    "entryType": "OEM Inspection / Track overlay",
    "action": "Inspect",
    "mileage": 12000,
    "months": 12,
    "trigger": "Factory steering/suspension inspection plus track/alignment use.",
    "basis": "Subaru OEM + severe-use",
    "amount": "Inspection item",
    "specification": "",
    "primaryUrl": "https://techinfo.subaru.com/stis/doc/warrantyBooklet/2022_war_and_maint_120721.PDF",
    "secondaryUrl": "https://techinfo.subaru.com/stis/doc/ownerManual/MSA5B2606A_STIS.pdf",
    "verification": "OEM inspection",
    "notes": "Curb/track impacts and aggressive alignment accelerate wear."
  },
  "zd8-brake-system-1a24a87e56": {
    "name": "Brake system",
    "category": "Brakes & safety",
    "severity": "critical",
    "entryType": "OEM Wear / Performance-package-specific",
    "action": "Inspect / service",
    "mileage": 12000,
    "months": 12,
    "trigger": "Factory inspections, track heat, vibration, pad/rotor wear.",
    "basis": "Subaru OEM / wear-based",
    "amount": "Standard brakes or Brembo package as equipped",
    "specification": "",
    "primaryUrl": "https://techinfo.subaru.com/stis/doc/warrantyBooklet/2022_war_and_maint_120721.PDF",
    "secondaryUrl": "https://www.prnewswire.com/news-releases/new-performance-focused-2024-subaru-brz-ts-debuts-at-subiefest-california-301883963.html",
    "verification": "Wear-based",
    "notes": "Do not assign fixed pad/rotor replacement mileage."
  },
  "zd8-shifter-linkage-driveshaft-cv-joints-and-center-support-41b8f82107": {
    "name": "Shifter linkage, driveshaft, CV joints & center support",
    "category": "Driveline",
    "severity": "important",
    "entryType": "Inspection / Severe-use",
    "action": "Inspect",
    "mileage": 30000,
    "months": 30,
    "trigger": "Clunk, vibration, torn CV boots, track/drift shock.",
    "basis": "Preventive inspection",
    "amount": "As required",
    "specification": "",
    "primaryUrl": "https://techinfo.subaru.com/stis/doc/warrantyBooklet/2022_war_and_maint_120721.PDF",
    "secondaryUrl": "https://www.ft86club.com/forums/",
    "verification": "Condition-based",
    "notes": "Clutch kicks/curbing can accelerate driveline wear."
  },
  "zd8-ignition-coils-and-boots-b80e198534": {
    "name": "Ignition coils & boots",
    "category": "Engine",
    "severity": "important",
    "entryType": "Condition-based",
    "action": "Diagnose / replace",
    "mileage": null,
    "months": null,
    "trigger": "Misfire, high-load breakup, coil fault.",
    "basis": "Condition-based",
    "amount": "4 coils",
    "specification": "",
    "primaryUrl": "https://techinfo.subaru.com/stis/doc/ownerManual/MSA5B2606A_STIS.pdf",
    "secondaryUrl": "https://www.ft86club.com/forums/",
    "verification": "Condition-based",
    "notes": "No blanket coil replacement mileage."
  },
  "zd8-timing-chain-guides-and-tensioner-d4a11dbe4c": {
    "name": "Timing chain, guides & tensioner",
    "category": "Engine",
    "severity": "important",
    "entryType": "Chain-driven engine / Condition",
    "action": "Inspect / repair by evidence",
    "mileage": null,
    "months": null,
    "trigger": "Persistent chain noise, oil-pressure issue, major front-cover work.",
    "basis": "Engine architecture",
    "amount": "Chain system",
    "specification": "",
    "primaryUrl": "https://techinfo.subaru.com/stis/doc/ownerManual/MSA5B2606A_STIS.pdf",
    "secondaryUrl": "https://www.ft86club.com/forums/",
    "verification": "Condition-based",
    "notes": "Do not invent a timing-belt-style interval."
  },
  "zd8-d-4s-direct-port-injection-system-4a3a1d7374": {
    "name": "D-4S direct + port injection system",
    "category": "General inspection",
    "severity": "important",
    "entryType": "Fuel-system-specific / Condition",
    "action": "Diagnose injectors / HPFP / LPFP by data",
    "mileage": null,
    "months": null,
    "trigger": "Hard start, misfire, rail-pressure fault, injector imbalance.",
    "basis": "FA24D architecture",
    "amount": "Port + direct injectors / high-pressure pump",
    "specification": "",
    "primaryUrl": "https://techinfo.subaru.com/stis/doc/ownerManual/MSA5B2606A_STIS.pdf",
    "secondaryUrl": "https://www.ft86club.com/forums/",
    "verification": "Condition-based",
    "notes": "No fixed walnut-blasting interval is appropriate for this dual-injection system."
  },
  "zd8-engine-oil-level-monitoring-bacb629526": {
    "name": "Engine oil level monitoring",
    "category": "Engine",
    "severity": "important",
    "entryType": "Owner check / Severe-use",
    "action": "Check dipstick frequently",
    "mileage": null,
    "months": null,
    "trigger": "Before long trips; more often with high RPM, track use or any consumption history.",
    "basis": "Owner manual + severe-use",
    "amount": "Dipstick check",
    "specification": "",
    "primaryUrl": "https://techinfo.subaru.com/stis/doc/ownerManual/MSA5B2606A_STIS.pdf",
    "secondaryUrl": "https://www.roadandtrack.com/news/a44362621/toyota-gr86-subaru-brz-fa24-potential-starvation-issue/",
    "verification": "Owner / track",
    "notes": "Oil level is especially important before track sessions."
  },
  "zd8-oil-pickup-excess-rtv-debris-7e94782560": {
    "name": "Oil pickup / excess RTV debris",
    "category": "Engine",
    "severity": "important",
    "entryType": "Known issue / Community evidence",
    "action": "Inspect by evidence; document oil-pan history",
    "mileage": null,
    "months": null,
    "trigger": "Low oil pressure, pan/front-cover work, debris in filter/pickup, owner concern.",
    "basis": "Documented community/shop observations",
    "amount": "Pickup screen / RTV sealant",
    "specification": "",
    "primaryUrl": "https://www.youtube.com/watch?v=E35rYvT4t6g",
    "secondaryUrl": "https://www.roadandtrack.com/news/a44362621/toyota-gr86-subaru-brz-fa24-potential-starvation-issue/",
    "verification": "Community — no recall",
    "notes": "Presence/severity varies by car; inspection is condition/history-driven."
  },
  "zd8-track-right-hand-corner-oil-pressure-behavior-3b9b1258be": {
    "name": "Track right-hand-corner oil-pressure behavior",
    "category": "Engine",
    "severity": "important",
    "entryType": "Track / Severe Use",
    "action": "Monitor pressure/temperature and plan track oiling strategy",
    "mileage": null,
    "months": null,
    "trigger": "HPDE/circuit use, especially sustained high-G right turns.",
    "basis": "Instrumented enthusiast testing",
    "amount": "Oil pressure / temperature logging",
    "specification": "",
    "primaryUrl": "https://www.roadandtrack.com/news/a44362621/toyota-gr86-subaru-brz-fa24-potential-starvation-issue/",
    "secondaryUrl": "https://www.ft86club.com/forums/",
    "verification": "Track-only evidence",
    "notes": "Subaru stated the FA24 is designed for road use; racing loads exceed normal duty."
  },
  "zd8-oil-cooler-baffled-pan-overfill-strategy-f7a113a16e": {
    "name": "Oil cooler / baffled pan / overfill strategy",
    "category": "Engine",
    "severity": "important",
    "entryType": "Modification-specific / Track",
    "action": "Evaluate only for measured severe-use need",
    "mileage": null,
    "months": null,
    "trigger": "Track oil temp/pressure data supports need.",
    "basis": "Modification-specific",
    "amount": "Aftermarket",
    "specification": "",
    "primaryUrl": "https://www.roadandtrack.com/news/a44362621/toyota-gr86-subaru-brz-fa24-potential-starvation-issue/",
    "secondaryUrl": "https://www.ft86club.com/forums/",
    "verification": "Modification-specific",
    "notes": "Not OEM-required street maintenance."
  },
  "zd8-torsen-lsd-operation-severe-use-heat-bd3293de9f": {
    "name": "Torsen LSD operation / severe-use heat",
    "category": "General inspection",
    "severity": "important",
    "entryType": "Driveline / Severe Use",
    "action": "Inspect fluid, leaks and operation",
    "mileage": null,
    "months": null,
    "trigger": "Track/drift use, diff overheating, noise or unknown history.",
    "basis": "Severe-use",
    "amount": "Torsen rear differential",
    "specification": "",
    "primaryUrl": "https://techinfo.subaru.com/stis/doc/warrantyBooklet/2022_war_and_maint_120721.PDF",
    "secondaryUrl": "https://www.ft86club.com/forums/",
    "verification": "Severe-use",
    "notes": "Normal brand-specific diff interval remains separate."
  },
  "zd8-wheel-studs-lug-threads-track-wheel-changes-833bdb0640": {
    "name": "Wheel studs / lug threads / track wheel changes",
    "category": "Chassis",
    "severity": "important",
    "entryType": "Severe-use / Inspection",
    "action": "Inspect threads and torque",
    "mileage": null,
    "months": null,
    "trigger": "Frequent wheel changes, spacers, track events.",
    "basis": "Track ownership",
    "amount": "Studs/lugs",
    "specification": "",
    "primaryUrl": "https://www.ft86club.com/forums/",
    "secondaryUrl": "https://www.gr86.org/",
    "verification": "Severe-use",
    "notes": "Repeated impact-gun abuse can damage threads."
  },
  "zd8-tire-wear-alignment-tpms-ba5918ea1a": {
    "name": "Tire wear / alignment / TPMS",
    "category": "Chassis",
    "severity": "critical",
    "entryType": "OEM Inspection / Track",
    "action": "Rotate/inspect; align by condition",
    "mileage": 6000,
    "months": 6,
    "trigger": "Factory tire service, uneven wear, track alignment or suspension changes.",
    "basis": "Subaru OEM + track",
    "amount": "Tires / TPMS",
    "specification": "",
    "primaryUrl": "https://techinfo.subaru.com/stis/doc/warrantyBooklet/2022_war_and_maint_120721.PDF",
    "secondaryUrl": "https://techinfo.subaru.com/stis/doc/ownerManual/MSA5B2606A_STIS.pdf",
    "verification": "OEM + condition",
    "notes": "Summer-tire temperature limitations matter in cold weather."
  },
  "zd8-active-safety-stereo-camera-calibration-8e4cff460c": {
    "name": "Active safety stereo camera calibration",
    "category": "Brakes & safety",
    "severity": "routine",
    "entryType": "ADAS / Repair-specific",
    "action": "Calibrate after relevant repairs",
    "mileage": null,
    "months": null,
    "trigger": "Windshield/camera replacement, collision, certain alignment/ride-height changes.",
    "basis": "ADAS architecture",
    "amount": "Stereo camera / control systems",
    "specification": "",
    "primaryUrl": "https://www.prnewswire.com/news-releases/new-performance-focused-2024-subaru-brz-ts-debuts-at-subiefest-california-301883963.html",
    "secondaryUrl": "https://techinfo.subaru.com/stis/doc/ownerManual/MSA5B2606A_STIS.pdf",
    "verification": "If equipped / period-specific",
    "notes": "No fixed maintenance interval."
  },
  "zd8-2022-rear-turn-signal-recall-23v-609-345d269ebe": {
    "name": "2022 rear turn-signal recall 23V-609",
    "category": "General inspection",
    "severity": "critical",
    "entryType": "Safety Recall",
    "action": "Verify recall completion",
    "mileage": null,
    "months": null,
    "trigger": "Certain 2022 GR86/BRZ VINs.",
    "basis": "NHTSA safety recall",
    "amount": "Rear combination lamps",
    "specification": "",
    "primaryUrl": "https://static.nhtsa.gov/odi/rcl/2023/RCAK-23V609-7844.pdf",
    "secondaryUrl": "https://www.subaru.com/recalls.html",
    "verification": "VIN-specific recall",
    "notes": "Not all 2022 cars are affected; verify VIN."
  },
  "zd8-track-autocross-baseline-inspection-0f15b2dad5": {
    "name": "Track / autocross baseline inspection",
    "category": "General inspection",
    "severity": "important",
    "entryType": "Severe Use",
    "action": "Inspect before/after events",
    "mileage": null,
    "months": null,
    "trigger": "HPDE, autocross, drift or repeated high-load use.",
    "basis": "Severe-use",
    "amount": "Inspection set",
    "specification": "",
    "primaryUrl": "https://www.roadandtrack.com/news/a44362621/toyota-gr86-subaru-brz-fa24-potential-starvation-issue/",
    "secondaryUrl": "https://www.ft86club.com/forums/",
    "verification": "Severe-use only",
    "notes": "Keep event-based maintenance separate from street OEM schedule."
  },
  "zd8-clutch-hydraulic-system-release-bearing-fork-bdac4d9c33": {
    "name": "Clutch hydraulic system / release bearing / fork",
    "category": "Driveline",
    "severity": "important",
    "entryType": "6MT Condition / Wear",
    "action": "Inspect / service by condition",
    "mileage": 30000,
    "months": 30,
    "trigger": "Pedal change, drag, slip, chatter, release noise.",
    "basis": "Manual-transmission ownership",
    "amount": "Clutch fluid shares brake-fluid spec; clutch assembly",
    "specification": "",
    "primaryUrl": "https://techinfo.subaru.com/stis/doc/ownerManual/MSA5B2606A_STIS.pdf",
    "secondaryUrl": "https://www.ft86club.com/forums/",
    "verification": "6MT only",
    "notes": "Track launches and heat accelerate clutch wear."
  },
  "zd8-6mt-synchro-shift-quality-fbdb294c80": {
    "name": "6MT synchro / shift quality",
    "category": "General inspection",
    "severity": "important",
    "entryType": "6MT Condition / Severe Use",
    "action": "Road-test and diagnose",
    "mileage": null,
    "months": null,
    "trigger": "Grinding/baulk, especially when cold or after track use.",
    "basis": "Manual-transmission ownership",
    "amount": "6-speed manual",
    "specification": "",
    "primaryUrl": "https://techinfo.subaru.com/stis/doc/ownerManual/MSA5B2606A_STIS.pdf",
    "secondaryUrl": "https://www.ft86club.com/forums/",
    "verification": "6MT only",
    "notes": "Fluid cannot repair physically worn synchros."
  },
  "zd8-brake-fluid-0bd4eea4b8": {
    "name": "Brake fluid",
    "category": "Brakes & safety",
    "severity": "important",
    "entryType": "OEM Scheduled / Severe-use",
    "action": "Replace",
    "mileage": 30000,
    "months": 30,
    "trigger": "Normal replacement around 30k; high-humidity/mountain or repeated track use warrants shorter service. Manual cars share brake/clutch fluid circuit requirements.",
    "basis": "Subaru OEM + severe-use",
    "amount": "~1 L service quantity",
    "specification": "",
    "primaryUrl": "https://techinfo.subaru.com/stis/doc/warrantyBooklet/2022_war_and_maint_120721.PDF",
    "secondaryUrl": "https://techinfo.subaru.com/stis/doc/ownerManual/MSA5B2606A_STIS.pdf",
    "verification": "OEM schedule / severe note",
    "notes": "Subaru severe-service guidance shortens brake/clutch-fluid service under specified conditions such as high humidity/mountain use; track heat may justify event-based service."
  },
  "zd8-automatic-transmission-fluid-f8e14294dd": {
    "name": "Automatic transmission fluid",
    "category": "Driveline",
    "severity": "important",
    "entryType": "Transmission-specific",
    "action": "Replace / service",
    "mileage": 60000,
    "months": 60,
    "trigger": "Toyota normal schedule is inspection-driven for gearbox fluid; Subaru BRZ schedule explicitly services ATF at 60k. Conservative enthusiast service is kept separate.",
    "basis": "Subaru OEM / preventive",
    "amount": "7.9 US qt / 7.5 L total reference; ATF WS",
    "specification": "",
    "primaryUrl": "https://techinfo.subaru.com/stis/doc/warrantyBooklet/2022_war_and_maint_120721.PDF",
    "secondaryUrl": "https://techinfo.subaru.com/stis/doc/ownerManual/MSA5B2606A_STIS.pdf",
    "verification": "Transmission-specific",
    "notes": "For Toyota 6MT, 30k is preventive owner guidance layered over factory inspection, not a Toyota replacement requirement."
  },
  "zd8-6at-temperature-shift-quality-3d3bfd039d": {
    "name": "6AT temperature / shift quality",
    "category": "General inspection",
    "severity": "important",
    "entryType": "6AT Condition / Severe Use",
    "action": "Monitor / service by condition",
    "mileage": null,
    "months": null,
    "trigger": "Track sessions, high ATF temperature, harsh shifts or flare.",
    "basis": "Automatic-transmission ownership",
    "amount": "6-speed automatic",
    "specification": "",
    "primaryUrl": "https://techinfo.subaru.com/stis/doc/ownerManual/MSA5B2606A_STIS.pdf",
    "secondaryUrl": "https://www.ft86club.com/forums/",
    "verification": "6AT only",
    "notes": "Track mode does not eliminate thermal limits."
  },
  "zd8-torsen-lsd-operation-severe-use-heat-95112ad49b": {
    "name": "Torsen LSD operation / severe-use heat",
    "category": "General inspection",
    "severity": "important",
    "entryType": "Driveline / Severe Use",
    "action": "Inspect fluid, leaks and operation",
    "mileage": 15000,
    "months": null,
    "trigger": "Track/drift use, diff overheating, noise or unknown history.",
    "basis": "Severe-use",
    "amount": "Torsen rear differential",
    "specification": "",
    "primaryUrl": "https://techinfo.subaru.com/stis/doc/warrantyBooklet/2022_war_and_maint_120721.PDF",
    "secondaryUrl": "https://www.ft86club.com/forums/",
    "verification": "Severe-use",
    "notes": "Normal brand-specific diff interval remains separate."
  },
  "zd8-brembo-performance-brakes-if-equipped-847c3504d1": {
    "name": "Brembo performance brakes — if equipped",
    "category": "Brakes & safety",
    "severity": "routine",
    "entryType": "Performance-package-specific",
    "action": "Inspect / service",
    "mileage": null,
    "months": null,
    "trigger": "Pad/rotor/caliper service; track use.",
    "basis": "Factory performance package",
    "amount": "4-piston front / 2-piston rear Brembo; larger rotors",
    "specification": "",
    "primaryUrl": "https://www.prnewswire.com/news-releases/new-performance-focused-2024-subaru-brz-ts-debuts-at-subiefest-california-301883963.html",
    "secondaryUrl": "https://techinfo.subaru.com/stis/doc/warrantyBooklet/2022_war_and_maint_120721.PDF",
    "verification": "Performance package / tS",
    "notes": "Do not order standard-brake parts for Brembo-equipped cars."
  },
  "zd8-performance-dampers-if-equipped-e33215b0ad": {
    "name": "Performance dampers — if equipped",
    "category": "Chassis",
    "severity": "routine",
    "entryType": "Performance-package-specific",
    "action": "Inspect for leakage / damage",
    "mileage": null,
    "months": 12,
    "trigger": "Impact, track use, suspension service.",
    "basis": "Factory performance package",
    "amount": "SACHS on Toyota; STI-tuned Hitachi on BRZ tS",
    "specification": "",
    "primaryUrl": "https://www.prnewswire.com/news-releases/new-performance-focused-2024-subaru-brz-ts-debuts-at-subiefest-california-301883963.html",
    "secondaryUrl": "https://techinfo.subaru.com/stis/doc/ownerManual/MSA5B2606A_STIS.pdf",
    "verification": "Performance variant",
    "notes": "Special-edition paint/trim does not change damper service logic."
  }
};

export const SUBARU_BRZ_SCHEDULES: Record<string, string[]> = {
  "research-zd8-brz-22-23-6mt": [
    "zd8-engine-oil-and-filter-55c2db0122",
    "zd8-brake-fluid-clutch-fluid-7e8b3c8032",
    "zd8-engine-air-filter-a2457a35ad",
    "zd8-cabin-microfilter-bf52b67755",
    "zd8-fuel-filter-8fce89d084",
    "zd8-manual-transmission-fluid-8e6a738a87",
    "zd8-rear-differential-fluid-68e307ffd9",
    "zd8-spark-plugs-610ca02db3",
    "zd8-oxygen-a-f-sensors-dddb6bf98e",
    "zd8-accessory-serpentine-belt-8afb76d17d",
    "zd8-belt-tensioner-and-idler-pulleys-9671971eb4",
    "zd8-engine-coolant-8de365ca94",
    "zd8-electric-power-steering-713d7c8d5b",
    "zd8-water-pump-e282bdb6e0",
    "zd8-thermostat-c127aeaa73",
    "zd8-thermostat-housing-coolant-necks-1fba6746f0",
    "zd8-radiator-condenser-cooling-stack-dd3e0cb9dc",
    "zd8-coolant-reservoir-cap-18c5b8ef63",
    "zd8-electric-cooling-fans-84ac6ac13a",
    "zd8-coolant-fuel-and-evap-hoses-cd711f74f5",
    "zd8-intake-ducts-vacuum-lines-and-pcv-4ee304c8fc",
    "zd8-chassis-bushings-ball-joints-and-wheel-bearings-905e89122a",
    "zd8-brake-system-1a24a87e56",
    "zd8-shifter-linkage-driveshaft-cv-joints-and-center-support-41b8f82107",
    "zd8-ignition-coils-and-boots-b80e198534",
    "zd8-timing-chain-guides-and-tensioner-d4a11dbe4c",
    "zd8-d-4s-direct-port-injection-system-4a3a1d7374",
    "zd8-engine-oil-level-monitoring-bacb629526",
    "zd8-oil-pickup-excess-rtv-debris-7e94782560",
    "zd8-track-right-hand-corner-oil-pressure-behavior-3b9b1258be",
    "zd8-oil-cooler-baffled-pan-overfill-strategy-f7a113a16e",
    "zd8-torsen-lsd-operation-severe-use-heat-bd3293de9f",
    "zd8-wheel-studs-lug-threads-track-wheel-changes-833bdb0640",
    "zd8-tire-wear-alignment-tpms-ba5918ea1a",
    "zd8-active-safety-stereo-camera-calibration-8e4cff460c",
    "zd8-2022-rear-turn-signal-recall-23v-609-345d269ebe",
    "zd8-track-autocross-baseline-inspection-0f15b2dad5",
    "zd8-clutch-hydraulic-system-release-bearing-fork-bdac4d9c33",
    "zd8-6mt-synchro-shift-quality-fbdb294c80"
  ],
  "research-zd8-brz-22-23-6at": [
    "zd8-engine-oil-and-filter-55c2db0122",
    "zd8-brake-fluid-0bd4eea4b8",
    "zd8-engine-air-filter-a2457a35ad",
    "zd8-cabin-microfilter-bf52b67755",
    "zd8-fuel-filter-8fce89d084",
    "zd8-automatic-transmission-fluid-f8e14294dd",
    "zd8-rear-differential-fluid-68e307ffd9",
    "zd8-spark-plugs-610ca02db3",
    "zd8-oxygen-a-f-sensors-dddb6bf98e",
    "zd8-accessory-serpentine-belt-8afb76d17d",
    "zd8-belt-tensioner-and-idler-pulleys-9671971eb4",
    "zd8-engine-coolant-8de365ca94",
    "zd8-electric-power-steering-713d7c8d5b",
    "zd8-water-pump-e282bdb6e0",
    "zd8-thermostat-c127aeaa73",
    "zd8-thermostat-housing-coolant-necks-1fba6746f0",
    "zd8-radiator-condenser-cooling-stack-dd3e0cb9dc",
    "zd8-coolant-reservoir-cap-18c5b8ef63",
    "zd8-electric-cooling-fans-84ac6ac13a",
    "zd8-coolant-fuel-and-evap-hoses-cd711f74f5",
    "zd8-intake-ducts-vacuum-lines-and-pcv-4ee304c8fc",
    "zd8-chassis-bushings-ball-joints-and-wheel-bearings-905e89122a",
    "zd8-brake-system-1a24a87e56",
    "zd8-shifter-linkage-driveshaft-cv-joints-and-center-support-41b8f82107",
    "zd8-ignition-coils-and-boots-b80e198534",
    "zd8-timing-chain-guides-and-tensioner-d4a11dbe4c",
    "zd8-d-4s-direct-port-injection-system-4a3a1d7374",
    "zd8-engine-oil-level-monitoring-bacb629526",
    "zd8-oil-pickup-excess-rtv-debris-7e94782560",
    "zd8-track-right-hand-corner-oil-pressure-behavior-3b9b1258be",
    "zd8-oil-cooler-baffled-pan-overfill-strategy-f7a113a16e",
    "zd8-torsen-lsd-operation-severe-use-heat-bd3293de9f",
    "zd8-wheel-studs-lug-threads-track-wheel-changes-833bdb0640",
    "zd8-tire-wear-alignment-tpms-ba5918ea1a",
    "zd8-active-safety-stereo-camera-calibration-8e4cff460c",
    "zd8-2022-rear-turn-signal-recall-23v-609-345d269ebe",
    "zd8-track-autocross-baseline-inspection-0f15b2dad5",
    "zd8-6at-temperature-shift-quality-3d3bfd039d"
  ],
  "research-zd8-brz-24-26-6mt": [
    "zd8-engine-oil-and-filter-55c2db0122",
    "zd8-brake-fluid-clutch-fluid-7e8b3c8032",
    "zd8-engine-air-filter-a2457a35ad",
    "zd8-cabin-microfilter-bf52b67755",
    "zd8-fuel-filter-8fce89d084",
    "zd8-manual-transmission-fluid-8e6a738a87",
    "zd8-rear-differential-fluid-68e307ffd9",
    "zd8-spark-plugs-610ca02db3",
    "zd8-oxygen-a-f-sensors-dddb6bf98e",
    "zd8-accessory-serpentine-belt-8afb76d17d",
    "zd8-belt-tensioner-and-idler-pulleys-9671971eb4",
    "zd8-engine-coolant-8de365ca94",
    "zd8-electric-power-steering-713d7c8d5b",
    "zd8-water-pump-e282bdb6e0",
    "zd8-thermostat-c127aeaa73",
    "zd8-thermostat-housing-coolant-necks-1fba6746f0",
    "zd8-radiator-condenser-cooling-stack-dd3e0cb9dc",
    "zd8-coolant-reservoir-cap-18c5b8ef63",
    "zd8-electric-cooling-fans-84ac6ac13a",
    "zd8-coolant-fuel-and-evap-hoses-cd711f74f5",
    "zd8-intake-ducts-vacuum-lines-and-pcv-4ee304c8fc",
    "zd8-chassis-bushings-ball-joints-and-wheel-bearings-905e89122a",
    "zd8-brake-system-1a24a87e56",
    "zd8-shifter-linkage-driveshaft-cv-joints-and-center-support-41b8f82107",
    "zd8-ignition-coils-and-boots-b80e198534",
    "zd8-timing-chain-guides-and-tensioner-d4a11dbe4c",
    "zd8-d-4s-direct-port-injection-system-4a3a1d7374",
    "zd8-engine-oil-level-monitoring-bacb629526",
    "zd8-oil-pickup-excess-rtv-debris-7e94782560",
    "zd8-track-right-hand-corner-oil-pressure-behavior-3b9b1258be",
    "zd8-oil-cooler-baffled-pan-overfill-strategy-f7a113a16e",
    "zd8-torsen-lsd-operation-severe-use-heat-bd3293de9f",
    "zd8-wheel-studs-lug-threads-track-wheel-changes-833bdb0640",
    "zd8-tire-wear-alignment-tpms-ba5918ea1a",
    "zd8-active-safety-stereo-camera-calibration-8e4cff460c",
    "zd8-2022-rear-turn-signal-recall-23v-609-345d269ebe",
    "zd8-track-autocross-baseline-inspection-0f15b2dad5",
    "zd8-clutch-hydraulic-system-release-bearing-fork-bdac4d9c33",
    "zd8-6mt-synchro-shift-quality-fbdb294c80"
  ],
  "research-zd8-brz-24-26-6at": [
    "zd8-engine-oil-and-filter-55c2db0122",
    "zd8-brake-fluid-0bd4eea4b8",
    "zd8-engine-air-filter-a2457a35ad",
    "zd8-cabin-microfilter-bf52b67755",
    "zd8-fuel-filter-8fce89d084",
    "zd8-automatic-transmission-fluid-f8e14294dd",
    "zd8-rear-differential-fluid-68e307ffd9",
    "zd8-spark-plugs-610ca02db3",
    "zd8-oxygen-a-f-sensors-dddb6bf98e",
    "zd8-accessory-serpentine-belt-8afb76d17d",
    "zd8-belt-tensioner-and-idler-pulleys-9671971eb4",
    "zd8-engine-coolant-8de365ca94",
    "zd8-electric-power-steering-713d7c8d5b",
    "zd8-water-pump-e282bdb6e0",
    "zd8-thermostat-c127aeaa73",
    "zd8-thermostat-housing-coolant-necks-1fba6746f0",
    "zd8-radiator-condenser-cooling-stack-dd3e0cb9dc",
    "zd8-coolant-reservoir-cap-18c5b8ef63",
    "zd8-electric-cooling-fans-84ac6ac13a",
    "zd8-coolant-fuel-and-evap-hoses-cd711f74f5",
    "zd8-intake-ducts-vacuum-lines-and-pcv-4ee304c8fc",
    "zd8-chassis-bushings-ball-joints-and-wheel-bearings-905e89122a",
    "zd8-brake-system-1a24a87e56",
    "zd8-shifter-linkage-driveshaft-cv-joints-and-center-support-41b8f82107",
    "zd8-ignition-coils-and-boots-b80e198534",
    "zd8-timing-chain-guides-and-tensioner-d4a11dbe4c",
    "zd8-d-4s-direct-port-injection-system-4a3a1d7374",
    "zd8-engine-oil-level-monitoring-bacb629526",
    "zd8-oil-pickup-excess-rtv-debris-7e94782560",
    "zd8-track-right-hand-corner-oil-pressure-behavior-3b9b1258be",
    "zd8-oil-cooler-baffled-pan-overfill-strategy-f7a113a16e",
    "zd8-torsen-lsd-operation-severe-use-heat-bd3293de9f",
    "zd8-wheel-studs-lug-threads-track-wheel-changes-833bdb0640",
    "zd8-tire-wear-alignment-tpms-ba5918ea1a",
    "zd8-active-safety-stereo-camera-calibration-8e4cff460c",
    "zd8-2022-rear-turn-signal-recall-23v-609-345d269ebe",
    "zd8-track-autocross-baseline-inspection-0f15b2dad5",
    "zd8-6at-temperature-shift-quality-3d3bfd039d"
  ],
  "research-zd8-brz-ts-24-26-6mt": [
    "zd8-engine-oil-and-filter-55c2db0122",
    "zd8-brake-fluid-clutch-fluid-7e8b3c8032",
    "zd8-engine-air-filter-a2457a35ad",
    "zd8-cabin-microfilter-bf52b67755",
    "zd8-fuel-filter-8fce89d084",
    "zd8-manual-transmission-fluid-8e6a738a87",
    "zd8-rear-differential-fluid-68e307ffd9",
    "zd8-spark-plugs-610ca02db3",
    "zd8-oxygen-a-f-sensors-dddb6bf98e",
    "zd8-accessory-serpentine-belt-8afb76d17d",
    "zd8-belt-tensioner-and-idler-pulleys-9671971eb4",
    "zd8-engine-coolant-8de365ca94",
    "zd8-electric-power-steering-713d7c8d5b",
    "zd8-water-pump-e282bdb6e0",
    "zd8-thermostat-c127aeaa73",
    "zd8-thermostat-housing-coolant-necks-1fba6746f0",
    "zd8-radiator-condenser-cooling-stack-dd3e0cb9dc",
    "zd8-coolant-reservoir-cap-18c5b8ef63",
    "zd8-electric-cooling-fans-84ac6ac13a",
    "zd8-coolant-fuel-and-evap-hoses-cd711f74f5",
    "zd8-intake-ducts-vacuum-lines-and-pcv-4ee304c8fc",
    "zd8-chassis-bushings-ball-joints-and-wheel-bearings-905e89122a",
    "zd8-brake-system-1a24a87e56",
    "zd8-shifter-linkage-driveshaft-cv-joints-and-center-support-41b8f82107",
    "zd8-ignition-coils-and-boots-b80e198534",
    "zd8-timing-chain-guides-and-tensioner-d4a11dbe4c",
    "zd8-d-4s-direct-port-injection-system-4a3a1d7374",
    "zd8-engine-oil-level-monitoring-bacb629526",
    "zd8-oil-pickup-excess-rtv-debris-7e94782560",
    "zd8-track-right-hand-corner-oil-pressure-behavior-3b9b1258be",
    "zd8-oil-cooler-baffled-pan-overfill-strategy-f7a113a16e",
    "zd8-torsen-lsd-operation-severe-use-heat-95112ad49b",
    "zd8-wheel-studs-lug-threads-track-wheel-changes-833bdb0640",
    "zd8-tire-wear-alignment-tpms-ba5918ea1a",
    "zd8-active-safety-stereo-camera-calibration-8e4cff460c",
    "zd8-2022-rear-turn-signal-recall-23v-609-345d269ebe",
    "zd8-track-autocross-baseline-inspection-0f15b2dad5",
    "zd8-clutch-hydraulic-system-release-bearing-fork-bdac4d9c33",
    "zd8-6mt-synchro-shift-quality-fbdb294c80",
    "zd8-brembo-performance-brakes-if-equipped-847c3504d1",
    "zd8-performance-dampers-if-equipped-e33215b0ad"
  ]
};

export const SUBARU_BRZ_ISSUES: EnhancedIssueRecord[] = [
  {
    "slug": "zd8-engine-oil-low-oil-level-under-high-rpm-severe-use",
    "platform": "ZD8",
    "scheduleIds": [
      "research-zd8-brz-22-23-6mt",
      "research-zd8-brz-22-23-6at",
      "research-zd8-brz-24-26-6mt",
      "research-zd8-brz-24-26-6at",
      "research-zd8-brz-ts-24-26-6mt"
    ],
    "years": [
      2022,
      2023,
      2024,
      2025,
      2026
    ],
    "system": "Engine oil",
    "issue": "Low oil level under high-RPM/severe use",
    "description": "Owner / severe-use · All",
    "symptoms": "Dipstick below full range or consumption after repeated high-rpm use",
    "typicalMileage": "Pre-event / frequent severe-use checks",
    "severity": "critical",
    "urgency": "watch",
    "evidence": "Community consensus",
    "evidenceLabel": "Owner / severe-use",
    "preventativeAction": "Check frequently; investigate abnormal consumption; start events at correct level.",
    "inspectionReminder": "Pre-event / frequent severe-use checks",
    "verification": "Owner/severe-use",
    "clarification": "Oil-level vigilance is maintenance, not proof of an engine defect.",
    "configuration": "BRZ 22-23 6MT / BRZ 22-23 6AT / BRZ 24-26 6MT / BRZ 24-26 6AT / BRZ tS-Yellow 24-26 6MT",
    "source": {
      "type": "Community consensus",
      "title": "Low oil level under high-RPM/severe use",
      "publisher": "techinfo.subaru.com",
      "url": "https://techinfo.subaru.com/stis/doc/ownerManual/MSA5B2606A_STIS.pdf",
      "note": "Owner/severe-use"
    },
    "sourceWorkbook": "Subaru ZD8 BRZ USDM Maintenance Schedules - Community Revised E46 Standard (2).xlsx"
  },
  {
    "slug": "zd8-track-oiling-oil-pressure-drops-in-some-sustained-right-hand-track-turns",
    "platform": "ZD8",
    "scheduleIds": [
      "research-zd8-brz-22-23-6mt",
      "research-zd8-brz-22-23-6at",
      "research-zd8-brz-24-26-6mt",
      "research-zd8-brz-24-26-6at",
      "research-zd8-brz-ts-24-26-6mt"
    ],
    "years": [
      2022,
      2023,
      2024,
      2025,
      2026
    ],
    "system": "Track oiling",
    "issue": "Oil-pressure drops in some sustained right-hand track turns",
    "description": "Instrumented community / severe-use · HPDE/circuit",
    "symptoms": "Logged pressure drop under high lateral load",
    "typicalMileage": "Every track event",
    "severity": "critical",
    "urgency": "watch",
    "evidence": "Community consensus",
    "evidenceLabel": "Instrumented community / severe-use",
    "preventativeAction": "Track cars should log pressure/temp and use an evidence-based oiling strategy.",
    "inspectionReminder": "Every track event",
    "verification": "Track evidence",
    "clarification": "Not established as a normal street-use defect or recall.",
    "configuration": "BRZ 22-23 6MT / BRZ 22-23 6AT / BRZ 24-26 6MT / BRZ 24-26 6AT / BRZ tS-Yellow 24-26 6MT",
    "source": {
      "type": "Community consensus",
      "title": "Oil-pressure drops in some sustained right-hand track turns",
      "publisher": "roadandtrack.com",
      "url": "https://www.roadandtrack.com/news/a44362621/toyota-gr86-subaru-brz-fa24-potential-starvation-issue/",
      "note": "Track evidence"
    },
    "sourceWorkbook": "Subaru ZD8 BRZ USDM Maintenance Schedules - Community Revised E46 Standard (2).xlsx"
  },
  {
    "slug": "zd8-oil-pickup-excess-rtv-sealant-debris-in-pickup-screen",
    "platform": "ZD8",
    "scheduleIds": [
      "research-zd8-brz-22-23-6mt",
      "research-zd8-brz-22-23-6at",
      "research-zd8-brz-24-26-6mt",
      "research-zd8-brz-24-26-6at",
      "research-zd8-brz-ts-24-26-6mt"
    ],
    "years": [
      2022,
      2023,
      2024,
      2025,
      2026
    ],
    "system": "Oil pickup",
    "issue": "Excess RTV/sealant debris in pickup screen",
    "description": "Community/shop evidence · All",
    "symptoms": "Debris discovered during pan inspection/filter work or pressure concern",
    "typicalMileage": "Condition/history",
    "severity": "important",
    "urgency": "watch",
    "evidence": "Community consensus",
    "evidenceLabel": "Community/shop evidence",
    "preventativeAction": "Inspect pickup when history/evidence justifies it and document reseal quality.",
    "inspectionReminder": "Condition/history",
    "verification": "Community/no recall",
    "clarification": "No official RTV recall located; incidence varies.",
    "configuration": "BRZ 22-23 6MT / BRZ 22-23 6AT / BRZ 24-26 6MT / BRZ 24-26 6AT / BRZ tS-Yellow 24-26 6MT",
    "source": {
      "type": "Community consensus",
      "title": "Excess RTV/sealant debris in pickup screen",
      "publisher": "youtube.com",
      "url": "https://www.youtube.com/watch?v=E35rYvT4t6g",
      "note": "Community/no recall"
    },
    "sourceWorkbook": "Subaru ZD8 BRZ USDM Maintenance Schedules - Community Revised E46 Standard (2).xlsx"
  },
  {
    "slug": "zd8-oil-modifications-unvalidated-baffle-oil-cooler-overfill-setup",
    "platform": "ZD8",
    "scheduleIds": [
      "research-zd8-brz-22-23-6mt",
      "research-zd8-brz-22-23-6at",
      "research-zd8-brz-24-26-6mt",
      "research-zd8-brz-24-26-6at",
      "research-zd8-brz-ts-24-26-6mt"
    ],
    "years": [
      2022,
      2023,
      2024,
      2025,
      2026
    ],
    "system": "Oil modifications",
    "issue": "Unvalidated baffle/oil-cooler/overfill setup",
    "description": "Modification-specific · Modified track cars",
    "symptoms": "Unknown oil capacity, leaks, pressure still unstable after modifications",
    "typicalMileage": "After modification / pre-event",
    "severity": "important",
    "urgency": "watch",
    "evidence": "Community consensus",
    "evidenceLabel": "Modification-specific",
    "preventativeAction": "Verify oil level/capacity and log pressure/temp after any oiling modification.",
    "inspectionReminder": "After modification / pre-event",
    "verification": "Modification-specific",
    "clarification": "Aftermarket parts are not automatically a complete solution.",
    "configuration": "BRZ 22-23 6MT / BRZ 22-23 6AT / BRZ 24-26 6MT / BRZ 24-26 6AT / BRZ tS-Yellow 24-26 6MT",
    "source": {
      "type": "Community consensus",
      "title": "Unvalidated baffle/oil-cooler/overfill setup",
      "publisher": "roadandtrack.com",
      "url": "https://www.roadandtrack.com/news/a44362621/toyota-gr86-subaru-brz-fa24-potential-starvation-issue/",
      "note": "Modification-specific"
    },
    "sourceWorkbook": "Subaru ZD8 BRZ USDM Maintenance Schedules - Community Revised E46 Standard (2).xlsx"
  },
  {
    "slug": "zd8-fuel-system-d-4s-injector-hpfp-lpfp-issue-misdiagnosed-as-carbon-buildup",
    "platform": "ZD8",
    "scheduleIds": [
      "research-zd8-brz-22-23-6mt",
      "research-zd8-brz-22-23-6at",
      "research-zd8-brz-24-26-6mt",
      "research-zd8-brz-24-26-6at",
      "research-zd8-brz-ts-24-26-6mt"
    ],
    "years": [
      2022,
      2023,
      2024,
      2025,
      2026
    ],
    "system": "Fuel system",
    "issue": "D-4S injector/HPFP/LPFP issue misdiagnosed as carbon buildup",
    "description": "Condition-based · All",
    "symptoms": "Hard start, misfire, rail-pressure or trim fault",
    "typicalMileage": "Symptoms",
    "severity": "important",
    "urgency": "watch",
    "evidence": "Community consensus",
    "evidenceLabel": "Condition-based",
    "preventativeAction": "Use scan/pressure/injector data before cleaning or replacement.",
    "inspectionReminder": "Symptoms",
    "verification": "Architecture",
    "clarification": "No fixed walnut-blasting interval is supported.",
    "configuration": "BRZ 22-23 6MT / BRZ 22-23 6AT / BRZ 24-26 6MT / BRZ 24-26 6AT / BRZ tS-Yellow 24-26 6MT",
    "source": {
      "type": "Community consensus",
      "title": "D-4S injector/HPFP/LPFP issue misdiagnosed as carbon buildup",
      "publisher": "techinfo.subaru.com",
      "url": "https://techinfo.subaru.com/stis/doc/ownerManual/MSA5B2606A_STIS.pdf",
      "note": "Architecture"
    },
    "sourceWorkbook": "Subaru ZD8 BRZ USDM Maintenance Schedules - Community Revised E46 Standard (2).xlsx"
  },
  {
    "slug": "zd8-engine-noise-normal-di-hpfp-ticking-mistaken-for-engine-failure",
    "platform": "ZD8",
    "scheduleIds": [
      "research-zd8-brz-22-23-6mt",
      "research-zd8-brz-22-23-6at",
      "research-zd8-brz-24-26-6mt",
      "research-zd8-brz-24-26-6at",
      "research-zd8-brz-ts-24-26-6mt"
    ],
    "years": [
      2022,
      2023,
      2024,
      2025,
      2026
    ],
    "system": "Engine noise",
    "issue": "Normal DI/HPFP ticking mistaken for engine failure",
    "description": "Diagnostic / owner education · All",
    "symptoms": "Fast ticking with no fault or oil-pressure issue",
    "typicalMileage": "PPI / symptoms",
    "severity": "routine",
    "urgency": "watch",
    "evidence": "Community consensus",
    "evidenceLabel": "Diagnostic / owner education",
    "preventativeAction": "Compare known-normal sound; investigate abnormal knock/misfire/codes.",
    "inspectionReminder": "PPI / symptoms",
    "verification": "Community/diagnostic",
    "clarification": "Deep knock or oil warning requires diagnosis.",
    "configuration": "BRZ 22-23 6MT / BRZ 22-23 6AT / BRZ 24-26 6MT / BRZ 24-26 6AT / BRZ tS-Yellow 24-26 6MT",
    "source": {
      "type": "Community consensus",
      "title": "Normal DI/HPFP ticking mistaken for engine failure",
      "publisher": "gr86.org",
      "url": "https://www.gr86.org/",
      "note": "Community/diagnostic"
    },
    "sourceWorkbook": "Subaru ZD8 BRZ USDM Maintenance Schedules - Community Revised E46 Standard (2).xlsx"
  },
  {
    "slug": "zd8-rear-lamps-2022-rear-turn-signal-intermittent-failure",
    "platform": "ZD8",
    "scheduleIds": [
      "research-zd8-brz-22-23-6mt",
      "research-zd8-brz-22-23-6at",
      "research-zd8-brz-24-26-6mt",
      "research-zd8-brz-24-26-6at",
      "research-zd8-brz-ts-24-26-6mt"
    ],
    "years": [
      2022,
      2023,
      2024,
      2025,
      2026
    ],
    "system": "Rear lamps",
    "issue": "2022 rear turn-signal intermittent failure",
    "description": "NHTSA Safety Recall · 2022 only",
    "symptoms": "Affected 2022 VIN; turn signal intermittently inoperative",
    "typicalMileage": "VIN recall check",
    "severity": "critical",
    "urgency": "urgent",
    "evidence": "Safety recall",
    "evidenceLabel": "NHTSA Safety Recall",
    "preventativeAction": "Verify 23V-609 completion; replace both rear combination lamps if affected.",
    "inspectionReminder": "VIN recall check",
    "verification": "Official recall",
    "clarification": "Not all 2022 cars are affected.",
    "configuration": "BRZ 22-23 6MT / BRZ 22-23 6AT / BRZ 24-26 6MT / BRZ 24-26 6AT / BRZ tS-Yellow 24-26 6MT",
    "source": {
      "type": "OEM",
      "title": "2022 rear turn-signal intermittent failure",
      "publisher": "static.nhtsa.gov",
      "url": "https://static.nhtsa.gov/odi/rcl/2023/RCAK-23V609-7844.pdf",
      "note": "Official recall"
    },
    "sourceWorkbook": "Subaru ZD8 BRZ USDM Maintenance Schedules - Community Revised E46 Standard (2).xlsx"
  },
  {
    "slug": "zd8-rear-differential-torsen-lsd-fluid-overheated-or-neglected-under-track-drift-use",
    "platform": "ZD8",
    "scheduleIds": [
      "research-zd8-brz-22-23-6mt",
      "research-zd8-brz-22-23-6at",
      "research-zd8-brz-24-26-6mt",
      "research-zd8-brz-24-26-6at",
      "research-zd8-brz-ts-24-26-6mt"
    ],
    "years": [
      2022,
      2023,
      2024,
      2025,
      2026
    ],
    "system": "Rear differential",
    "issue": "Torsen LSD fluid overheated or neglected under track/drift use",
    "description": "Severe-use · All / track strongest",
    "symptoms": "Whine, burnt fluid, repeated track/drift heat",
    "typicalMileage": "Pre/post-event",
    "severity": "important",
    "urgency": "watch",
    "evidence": "Community consensus",
    "evidenceLabel": "Severe-use",
    "preventativeAction": "Follow brand normal schedule and shorten fluid changes based on severe use.",
    "inspectionReminder": "Pre/post-event",
    "verification": "OEM + severe-use",
    "clarification": "Toyota normal schedule is inspection-driven; Subaru specifies 60k/4yr replacement.",
    "configuration": "BRZ 22-23 6MT / BRZ 22-23 6AT / BRZ 24-26 6MT / BRZ 24-26 6AT / BRZ tS-Yellow 24-26 6MT",
    "source": {
      "type": "Community consensus",
      "title": "Torsen LSD fluid overheated or neglected under track/drift use",
      "publisher": "techinfo.subaru.com",
      "url": "https://techinfo.subaru.com/stis/doc/warrantyBooklet/2022_war_and_maint_120721.PDF",
      "note": "OEM + severe-use"
    },
    "sourceWorkbook": "Subaru ZD8 BRZ USDM Maintenance Schedules - Community Revised E46 Standard (2).xlsx"
  },
  {
    "slug": "zd8-wheel-hardware-stud-lug-thread-damage-after-frequent-wheel-changes",
    "platform": "ZD8",
    "scheduleIds": [
      "research-zd8-brz-22-23-6mt",
      "research-zd8-brz-22-23-6at",
      "research-zd8-brz-24-26-6mt",
      "research-zd8-brz-24-26-6at",
      "research-zd8-brz-ts-24-26-6mt"
    ],
    "years": [
      2022,
      2023,
      2024,
      2025,
      2026
    ],
    "system": "Wheel hardware",
    "issue": "Stud/lug thread damage after frequent wheel changes",
    "description": "Track/severe-use · Track/autocross",
    "symptoms": "Cross-threaded lug, stretched stud, inconsistent torque",
    "typicalMileage": "Every tire change/event",
    "severity": "important",
    "urgency": "watch",
    "evidence": "Community consensus",
    "evidenceLabel": "Track/severe-use",
    "preventativeAction": "Inspect threads and seats; use correct torque; replace damaged hardware.",
    "inspectionReminder": "Every tire change/event",
    "verification": "Community severe-use",
    "clarification": "Impact-gun abuse is not a factory defect.",
    "configuration": "BRZ 22-23 6MT / BRZ 22-23 6AT / BRZ 24-26 6MT / BRZ 24-26 6AT / BRZ tS-Yellow 24-26 6MT",
    "source": {
      "type": "Community consensus",
      "title": "Stud/lug thread damage after frequent wheel changes",
      "publisher": "ft86club.com",
      "url": "https://www.ft86club.com/forums/",
      "note": "Community severe-use"
    },
    "sourceWorkbook": "Subaru ZD8 BRZ USDM Maintenance Schedules - Community Revised E46 Standard (2).xlsx"
  },
  {
    "slug": "zd8-underbody-chassis-bent-arm-toe-link-or-undertray-damage-from-curbing",
    "platform": "ZD8",
    "scheduleIds": [
      "research-zd8-brz-22-23-6mt",
      "research-zd8-brz-22-23-6at",
      "research-zd8-brz-24-26-6mt",
      "research-zd8-brz-24-26-6at",
      "research-zd8-brz-ts-24-26-6mt"
    ],
    "years": [
      2022,
      2023,
      2024,
      2025,
      2026
    ],
    "system": "Underbody/chassis",
    "issue": "Bent arm/toe link or undertray damage from curbing",
    "description": "Impact/severe-use · All",
    "symptoms": "Uneven alignment, tire wear, damaged aero panels",
    "typicalMileage": "After impact",
    "severity": "important",
    "urgency": "watch",
    "evidence": "Community consensus",
    "evidenceLabel": "Impact/severe-use",
    "preventativeAction": "Lift-inspect and align after major curb/impact event.",
    "inspectionReminder": "After impact",
    "verification": "Condition/severe",
    "clarification": "Aggressive alignment alone is not damage.",
    "configuration": "BRZ 22-23 6MT / BRZ 22-23 6AT / BRZ 24-26 6MT / BRZ 24-26 6AT / BRZ tS-Yellow 24-26 6MT",
    "source": {
      "type": "Community consensus",
      "title": "Bent arm/toe link or undertray damage from curbing",
      "publisher": "ft86club.com",
      "url": "https://www.ft86club.com/forums/",
      "note": "Condition/severe"
    },
    "sourceWorkbook": "Subaru ZD8 BRZ USDM Maintenance Schedules - Community Revised E46 Standard (2).xlsx"
  },
  {
    "slug": "zd8-cooling-high-oil-coolant-temperatures-during-long-track-sessions",
    "platform": "ZD8",
    "scheduleIds": [
      "research-zd8-brz-22-23-6mt",
      "research-zd8-brz-22-23-6at",
      "research-zd8-brz-24-26-6mt",
      "research-zd8-brz-24-26-6at",
      "research-zd8-brz-ts-24-26-6mt"
    ],
    "years": [
      2022,
      2023,
      2024,
      2025,
      2026
    ],
    "system": "Cooling",
    "issue": "High oil/coolant temperatures during long track sessions",
    "description": "Severe-use · Track",
    "symptoms": "Rising temperatures or heat-related performance reduction",
    "typicalMileage": "Every track event",
    "severity": "important",
    "urgency": "watch",
    "evidence": "Community consensus",
    "evidenceLabel": "Severe-use",
    "preventativeAction": "Monitor temps, use proper cool-down and add cooling hardware only when data supports it.",
    "inspectionReminder": "Every track event",
    "verification": "Track/severe",
    "clarification": "Street cooling is designed around road duty.",
    "configuration": "BRZ 22-23 6MT / BRZ 22-23 6AT / BRZ 24-26 6MT / BRZ 24-26 6AT / BRZ tS-Yellow 24-26 6MT",
    "source": {
      "type": "Community consensus",
      "title": "High oil/coolant temperatures during long track sessions",
      "publisher": "ft86club.com",
      "url": "https://www.ft86club.com/forums/",
      "note": "Track/severe"
    },
    "sourceWorkbook": "Subaru ZD8 BRZ USDM Maintenance Schedules - Community Revised E46 Standard (2).xlsx"
  },
  {
    "slug": "zd8-battery-electronics-low-battery-voltage-creating-multiple-warnings",
    "platform": "ZD8",
    "scheduleIds": [
      "research-zd8-brz-22-23-6mt",
      "research-zd8-brz-22-23-6at",
      "research-zd8-brz-24-26-6mt",
      "research-zd8-brz-24-26-6at",
      "research-zd8-brz-ts-24-26-6mt"
    ],
    "years": [
      2022,
      2023,
      2024,
      2025,
      2026
    ],
    "system": "Battery/electronics",
    "issue": "Low battery voltage creating multiple warnings",
    "description": "Condition-based · All",
    "symptoms": "Slow crank, cluster/ADAS warnings after storage",
    "typicalMileage": "Annual / storage",
    "severity": "important",
    "urgency": "watch",
    "evidence": "Community consensus",
    "evidenceLabel": "Condition-based",
    "preventativeAction": "Test battery/charging; restore voltage before module diagnosis.",
    "inspectionReminder": "Annual / storage",
    "verification": "Condition",
    "clarification": "Low voltage can create misleading faults.",
    "configuration": "BRZ 22-23 6MT / BRZ 22-23 6AT / BRZ 24-26 6MT / BRZ 24-26 6AT / BRZ tS-Yellow 24-26 6MT",
    "source": {
      "type": "Community consensus",
      "title": "Low battery voltage creating multiple warnings",
      "publisher": "techinfo.subaru.com",
      "url": "https://techinfo.subaru.com/stis/doc/ownerManual/MSA5B2606A_STIS.pdf",
      "note": "Condition"
    },
    "sourceWorkbook": "Subaru ZD8 BRZ USDM Maintenance Schedules - Community Revised E46 Standard (2).xlsx"
  },
  {
    "slug": "zd8-tires-alignment-inner-edge-tire-wear-from-aggressive-camber-toe",
    "platform": "ZD8",
    "scheduleIds": [
      "research-zd8-brz-22-23-6mt",
      "research-zd8-brz-22-23-6at",
      "research-zd8-brz-24-26-6mt",
      "research-zd8-brz-24-26-6at",
      "research-zd8-brz-ts-24-26-6mt"
    ],
    "years": [
      2022,
      2023,
      2024,
      2025,
      2026
    ],
    "system": "Tires/alignment",
    "issue": "Inner-edge tire wear from aggressive camber/toe",
    "description": "Setup / condition · Lowered/track-aligned",
    "symptoms": "Inner shoulder worn faster than visible outer tread",
    "typicalMileage": "Monthly / track",
    "severity": "important",
    "urgency": "watch",
    "evidence": "Community consensus",
    "evidenceLabel": "Setup / condition",
    "preventativeAction": "Measure alignment and inspect full tread width regularly.",
    "inspectionReminder": "Monthly / track",
    "verification": "Modification/severe",
    "clarification": "Performance alignment trades tire life for grip.",
    "configuration": "BRZ 22-23 6MT / BRZ 22-23 6AT / BRZ 24-26 6MT / BRZ 24-26 6AT / BRZ tS-Yellow 24-26 6MT",
    "source": {
      "type": "Community consensus",
      "title": "Inner-edge tire wear from aggressive camber/toe",
      "publisher": "ft86club.com",
      "url": "https://www.ft86club.com/forums/",
      "note": "Modification/severe"
    },
    "sourceWorkbook": "Subaru ZD8 BRZ USDM Maintenance Schedules - Community Revised E46 Standard (2).xlsx"
  },
  {
    "slug": "zd8-clutch-clutch-release-bearing-or-hydraulic-wear",
    "platform": "ZD8",
    "scheduleIds": [
      "research-zd8-brz-22-23-6mt",
      "research-zd8-brz-24-26-6mt",
      "research-zd8-brz-ts-24-26-6mt"
    ],
    "years": [
      2022,
      2023,
      2024,
      2025,
      2026
    ],
    "system": "Clutch",
    "issue": "Clutch/release bearing or hydraulic wear",
    "description": "Wear/track · 6MT",
    "symptoms": "Pedal change, release noise, drag or slip",
    "typicalMileage": "Symptoms / 30k review",
    "severity": "important",
    "urgency": "watch",
    "evidence": "Community consensus",
    "evidenceLabel": "Wear/track",
    "preventativeAction": "Inspect hydraulics, release mechanism and clutch; confirm full disengagement.",
    "inspectionReminder": "Symptoms / 30k review",
    "verification": "Community/wear",
    "clarification": "Track starts and heat accelerate wear.",
    "configuration": "BRZ 22-23 6MT / BRZ 24-26 6MT / BRZ tS-Yellow 24-26 6MT",
    "source": {
      "type": "Community consensus",
      "title": "Clutch/release bearing or hydraulic wear",
      "publisher": "ft86club.com",
      "url": "https://www.ft86club.com/forums/",
      "note": "Community/wear"
    },
    "sourceWorkbook": "Subaru ZD8 BRZ USDM Maintenance Schedules - Community Revised E46 Standard (2).xlsx"
  },
  {
    "slug": "zd8-6mt-synchro-baulk-grind-after-severe-use",
    "platform": "ZD8",
    "scheduleIds": [
      "research-zd8-brz-22-23-6mt",
      "research-zd8-brz-24-26-6mt",
      "research-zd8-brz-ts-24-26-6mt"
    ],
    "years": [
      2022,
      2023,
      2024,
      2025,
      2026
    ],
    "system": "6MT",
    "issue": "Synchro baulk/grind after severe use",
    "description": "Wear/severe-use · 6MT",
    "symptoms": "Persistent shift resistance or grind",
    "typicalMileage": "PPI / post-event",
    "severity": "important",
    "urgency": "watch",
    "evidence": "Community consensus",
    "evidenceLabel": "Wear/severe-use",
    "preventativeAction": "Verify clutch release and correct gear oil; diagnose synchros if persistent.",
    "inspectionReminder": "PPI / post-event",
    "verification": "Community/wear",
    "clarification": "Fluid cannot repair worn synchros.",
    "configuration": "BRZ 22-23 6MT / BRZ 24-26 6MT / BRZ tS-Yellow 24-26 6MT",
    "source": {
      "type": "Community consensus",
      "title": "Synchro baulk/grind after severe use",
      "publisher": "ft86club.com",
      "url": "https://www.ft86club.com/forums/",
      "note": "Community/wear"
    },
    "sourceWorkbook": "Subaru ZD8 BRZ USDM Maintenance Schedules - Community Revised E46 Standard (2).xlsx"
  },
  {
    "slug": "zd8-shifter-aftermarket-short-shifter-bushing-installation-quality",
    "platform": "ZD8",
    "scheduleIds": [
      "research-zd8-brz-22-23-6mt",
      "research-zd8-brz-24-26-6mt",
      "research-zd8-brz-ts-24-26-6mt"
    ],
    "years": [
      2022,
      2023,
      2024,
      2025,
      2026
    ],
    "system": "Shifter",
    "issue": "Aftermarket short-shifter/bushing installation quality",
    "description": "Modification-specific · Modified 6MT",
    "symptoms": "Binding, play, noise or poor centering",
    "typicalMileage": "PPI / after modification",
    "severity": "important",
    "urgency": "watch",
    "evidence": "Community consensus",
    "evidenceLabel": "Modification-specific",
    "preventativeAction": "Inspect linkage, fasteners and installation quality.",
    "inspectionReminder": "PPI / after modification",
    "verification": "Modification-specific",
    "clarification": "Subaru Series.Purple STI shifter is factory-backed hardware.",
    "configuration": "BRZ 22-23 6MT / BRZ 24-26 6MT / BRZ tS-Yellow 24-26 6MT",
    "source": {
      "type": "Community consensus",
      "title": "Aftermarket short-shifter/bushing installation quality",
      "publisher": "gr86.org",
      "url": "https://www.gr86.org/",
      "note": "Modification-specific"
    },
    "sourceWorkbook": "Subaru ZD8 BRZ USDM Maintenance Schedules - Community Revised E46 Standard (2).xlsx"
  },
  {
    "slug": "zd8-6at-atf-overheating-degradation-from-repeated-track-use",
    "platform": "ZD8",
    "scheduleIds": [
      "research-zd8-brz-22-23-6at",
      "research-zd8-brz-24-26-6at"
    ],
    "years": [
      2022,
      2023,
      2024,
      2025,
      2026
    ],
    "system": "6AT",
    "issue": "ATF overheating/degradation from repeated track use",
    "description": "Severe-use · 6AT",
    "symptoms": "Shift-quality change or high ATF temp after sessions",
    "typicalMileage": "Track / street service interval",
    "severity": "important",
    "urgency": "watch",
    "evidence": "Community consensus",
    "evidenceLabel": "Severe-use",
    "preventativeAction": "Monitor/cool as needed; service ATF WS based on use/history.",
    "inspectionReminder": "Track / street service interval",
    "verification": "Severe-use",
    "clarification": "Street schedule does not represent repeated circuit heat.",
    "configuration": "BRZ 22-23 6AT / BRZ 24-26 6AT",
    "source": {
      "type": "Community consensus",
      "title": "ATF overheating/degradation from repeated track use",
      "publisher": "ft86club.com",
      "url": "https://www.ft86club.com/forums/",
      "note": "Severe-use"
    },
    "sourceWorkbook": "Subaru ZD8 BRZ USDM Maintenance Schedules - Community Revised E46 Standard (2).xlsx"
  },
  {
    "slug": "zd8-6at-harsh-shift-flare-diagnosed-without-scan-fluid-level-history",
    "platform": "ZD8",
    "scheduleIds": [
      "research-zd8-brz-22-23-6at",
      "research-zd8-brz-24-26-6at"
    ],
    "years": [
      2022,
      2023,
      2024,
      2025,
      2026
    ],
    "system": "6AT",
    "issue": "Harsh shift/flare diagnosed without scan/fluid-level history",
    "description": "Condition-based · 6AT",
    "symptoms": "Flare, delayed shift, stored transmission fault",
    "typicalMileage": "Symptoms / PPI",
    "severity": "important",
    "urgency": "watch",
    "evidence": "Community consensus",
    "evidenceLabel": "Condition-based",
    "preventativeAction": "Scan TCM and verify correct fluid/level before major repair.",
    "inspectionReminder": "Symptoms / PPI",
    "verification": "Condition",
    "clarification": "Temperature-based fill procedure matters.",
    "configuration": "BRZ 22-23 6AT / BRZ 24-26 6AT",
    "source": {
      "type": "Community consensus",
      "title": "Harsh shift/flare diagnosed without scan/fluid-level history",
      "publisher": "techinfo.subaru.com",
      "url": "https://techinfo.subaru.com/stis/doc/warrantyBooklet/2022_war_and_maint_120721.PDF",
      "note": "Condition"
    },
    "sourceWorkbook": "Subaru ZD8 BRZ USDM Maintenance Schedules - Community Revised E46 Standard (2).xlsx"
  },
  {
    "slug": "zd8-adas-stereo-camera-calibration-lost-after-windshield-collision-suspension-work",
    "platform": "ZD8",
    "scheduleIds": [
      "research-zd8-brz-22-23-6at",
      "research-zd8-brz-24-26-6mt",
      "research-zd8-brz-24-26-6at",
      "research-zd8-brz-ts-24-26-6mt"
    ],
    "years": [
      2022,
      2023,
      2024,
      2025,
      2026
    ],
    "system": "ADAS",
    "issue": "Stereo-camera calibration lost after windshield/collision/suspension work",
    "description": "Repair-specific · ADAS-equipped",
    "symptoms": "ADAS warning or poor detection after repair",
    "typicalMileage": "After relevant repair",
    "severity": "important",
    "urgency": "watch",
    "evidence": "Community consensus",
    "evidenceLabel": "Repair-specific",
    "preventativeAction": "Perform exact brand calibration/aiming procedure.",
    "inspectionReminder": "After relevant repair",
    "verification": "Factory architecture",
    "clarification": "No periodic calibration interval.",
    "configuration": "BRZ 22-23 6AT / BRZ 24-26 6MT / BRZ 24-26 6AT / BRZ tS-Yellow 24-26 6MT",
    "source": {
      "type": "Community consensus",
      "title": "Stereo-camera calibration lost after windshield/collision/suspension work",
      "publisher": "prnewswire.com",
      "url": "https://www.prnewswire.com/news-releases/new-performance-focused-2024-subaru-brz-ts-debuts-at-subiefest-california-301883963.html",
      "note": "Factory architecture"
    },
    "sourceWorkbook": "Subaru ZD8 BRZ USDM Maintenance Schedules - Community Revised E46 Standard (2).xlsx"
  },
  {
    "slug": "zd8-adas-ride-height-alignment-modification-changes-calibration-assumptions",
    "platform": "ZD8",
    "scheduleIds": [
      "research-zd8-brz-22-23-6at",
      "research-zd8-brz-24-26-6mt",
      "research-zd8-brz-24-26-6at",
      "research-zd8-brz-ts-24-26-6mt"
    ],
    "years": [
      2022,
      2023,
      2024,
      2025,
      2026
    ],
    "system": "ADAS",
    "issue": "Ride-height/alignment modification changes calibration assumptions",
    "description": "Modification-specific · ADAS-equipped",
    "symptoms": "Warning after lowering/alignment or steering-angle mismatch",
    "typicalMileage": "After suspension modification",
    "severity": "important",
    "urgency": "watch",
    "evidence": "Community consensus",
    "evidenceLabel": "Modification-specific",
    "preventativeAction": "Recheck steering angle and required camera calibration after significant geometry changes.",
    "inspectionReminder": "After suspension modification",
    "verification": "Modification-specific",
    "clarification": "Do not disable safety systems as a substitute for calibration.",
    "configuration": "BRZ 22-23 6AT / BRZ 24-26 6MT / BRZ 24-26 6AT / BRZ tS-Yellow 24-26 6MT",
    "source": {
      "type": "Community consensus",
      "title": "Ride-height/alignment modification changes calibration assumptions",
      "publisher": "prnewswire.com",
      "url": "https://www.prnewswire.com/news-releases/new-performance-focused-2024-subaru-brz-ts-debuts-at-subiefest-california-301883963.html",
      "note": "Modification-specific"
    },
    "sourceWorkbook": "Subaru ZD8 BRZ USDM Maintenance Schedules - Community Revised E46 Standard (2).xlsx"
  },
  {
    "slug": "zd8-eyesight-2024-manual-eyesight-newly-standard",
    "platform": "ZD8",
    "scheduleIds": [
      "research-zd8-brz-24-26-6mt",
      "research-zd8-brz-24-26-6at"
    ],
    "years": [
      2024,
      2025,
      2026
    ],
    "system": "EyeSight",
    "issue": "2024+ manual EyeSight newly standard",
    "description": "Production distinction · 2024–26 6MT",
    "symptoms": "Manual car treated as pre-2024 non-EyeSight configuration",
    "typicalMileage": "PPI / repair",
    "severity": "important",
    "urgency": "watch",
    "evidence": "Community consensus",
    "evidenceLabel": "Production distinction",
    "preventativeAction": "Use 2024+ EyeSight repair/calibration procedures.",
    "inspectionReminder": "PPI / repair",
    "verification": "Subaru production-specific",
    "clarification": "First manual-transmission EyeSight application in BRZ.",
    "configuration": "BRZ 24-26 6MT / BRZ 24-26 6AT",
    "source": {
      "type": "Community consensus",
      "title": "2024+ manual EyeSight newly standard",
      "publisher": "prnewswire.com",
      "url": "https://www.prnewswire.com/news-releases/new-performance-focused-2024-subaru-brz-ts-debuts-at-subiefest-california-301883963.html",
      "note": "Subaru production-specific"
    },
    "sourceWorkbook": "Subaru ZD8 BRZ USDM Maintenance Schedules - Community Revised E46 Standard (2).xlsx"
  },
  {
    "slug": "zd8-brembo-brakes-standard-brake-pads-rotors-ordered-for-performance-hardware",
    "platform": "ZD8",
    "scheduleIds": [
      "research-zd8-brz-ts-24-26-6mt"
    ],
    "years": [
      2024,
      2025,
      2026
    ],
    "system": "Brembo brakes",
    "issue": "Standard-brake pads/rotors ordered for performance hardware",
    "description": "Configuration-specific · Performance hardware",
    "symptoms": "Parts do not fit or dimensions mismatch",
    "typicalMileage": "Every brake service",
    "severity": "important",
    "urgency": "watch",
    "evidence": "Community consensus",
    "evidenceLabel": "Configuration-specific",
    "preventativeAction": "Verify VIN/trim/package before ordering service parts.",
    "inspectionReminder": "Every brake service",
    "verification": "Factory variant",
    "clarification": "Brembo package changes service parts, not engine interval.",
    "configuration": "BRZ tS-Yellow 24-26 6MT",
    "source": {
      "type": "Community consensus",
      "title": "Standard-brake pads/rotors ordered for performance hardware",
      "publisher": "prnewswire.com",
      "url": "https://www.prnewswire.com/news-releases/new-performance-focused-2024-subaru-brz-ts-debuts-at-subiefest-california-301883963.html",
      "note": "Factory variant"
    },
    "sourceWorkbook": "Subaru ZD8 BRZ USDM Maintenance Schedules - Community Revised E46 Standard (2).xlsx"
  },
  {
    "slug": "zd8-brembo-brakes-track-heat-stresses-fluid-pads-rotors-dust-boots",
    "platform": "ZD8",
    "scheduleIds": [
      "research-zd8-brz-ts-24-26-6mt"
    ],
    "years": [
      2024,
      2025,
      2026
    ],
    "system": "Brembo brakes",
    "issue": "Track heat stresses fluid/pads/rotors/dust boots",
    "description": "Severe-use · Performance hardware",
    "symptoms": "Discolored fluid, thin pads, rotor cracking, damaged boots",
    "typicalMileage": "Every event",
    "severity": "important",
    "urgency": "watch",
    "evidence": "Community consensus",
    "evidenceLabel": "Severe-use",
    "preventativeAction": "Inspect after events; use track-appropriate consumables where legal/safe.",
    "inspectionReminder": "Every event",
    "verification": "Track/severe",
    "clarification": "Larger brakes still require track inspection.",
    "configuration": "BRZ tS-Yellow 24-26 6MT",
    "source": {
      "type": "Community consensus",
      "title": "Track heat stresses fluid/pads/rotors/dust boots",
      "publisher": "prnewswire.com",
      "url": "https://www.prnewswire.com/news-releases/new-performance-focused-2024-subaru-brz-ts-debuts-at-subiefest-california-301883963.html",
      "note": "Track/severe"
    },
    "sourceWorkbook": "Subaru ZD8 BRZ USDM Maintenance Schedules - Community Revised E46 Standard (2).xlsx"
  },
  {
    "slug": "zd8-performance-dampers-sachs-hitachi-damper-leakage-or-impact-damage",
    "platform": "ZD8",
    "scheduleIds": [
      "research-zd8-brz-ts-24-26-6mt"
    ],
    "years": [
      2024,
      2025,
      2026
    ],
    "system": "Performance dampers",
    "issue": "SACHS/Hitachi damper leakage or impact damage",
    "description": "Condition-based · Performance hardware",
    "symptoms": "Damper leak, uneven response, impact history",
    "typicalMileage": "Annual / impact",
    "severity": "important",
    "urgency": "watch",
    "evidence": "Community consensus",
    "evidenceLabel": "Condition-based",
    "preventativeAction": "Inspect damper/mounts and align after replacement.",
    "inspectionReminder": "Annual / impact",
    "verification": "Factory variant",
    "clarification": "No fixed replacement mileage.",
    "configuration": "BRZ tS-Yellow 24-26 6MT",
    "source": {
      "type": "Community consensus",
      "title": "SACHS/Hitachi damper leakage or impact damage",
      "publisher": "prnewswire.com",
      "url": "https://www.prnewswire.com/news-releases/new-performance-focused-2024-subaru-brz-ts-debuts-at-subiefest-california-301883963.html",
      "note": "Factory variant"
    },
    "sourceWorkbook": "Subaru ZD8 BRZ USDM Maintenance Schedules - Community Revised E46 Standard (2).xlsx"
  },
  {
    "slug": "zd8-ts-hardware-ts-series-yellow-parts-misidentified-as-standard-limited-parts",
    "platform": "ZD8",
    "scheduleIds": [
      "research-zd8-brz-ts-24-26-6mt"
    ],
    "years": [
      2024,
      2025,
      2026
    ],
    "system": "tS hardware",
    "issue": "tS/Series.Yellow parts misidentified as standard Limited parts",
    "description": "Factory variant · tS / Series.Yellow",
    "symptoms": "Wrong pads/rotors/dampers or missing special hardware",
    "typicalMileage": "PPI / service",
    "severity": "important",
    "urgency": "watch",
    "evidence": "Community consensus",
    "evidenceLabel": "Factory variant",
    "preventativeAction": "Verify tS hardware and use correct service parts.",
    "inspectionReminder": "PPI / service",
    "verification": "Factory performance variant",
    "clarification": "2026 Series.Yellow is tS-based.",
    "configuration": "BRZ tS-Yellow 24-26 6MT",
    "source": {
      "type": "Community consensus",
      "title": "tS/Series.Yellow parts misidentified as standard Limited parts",
      "publisher": "prnewswire.com",
      "url": "https://www.prnewswire.com/news-releases/new-performance-focused-2024-subaru-brz-ts-debuts-at-subiefest-california-301883963.html",
      "note": "Factory performance variant"
    },
    "sourceWorkbook": "Subaru ZD8 BRZ USDM Maintenance Schedules - Community Revised E46 Standard (2).xlsx"
  }
];

export const SUBARU_BRZ_INSIGHTS: EnhancedInsightRecord[] = [
  {
    "slug": "zd8-model-year-2022-2023",
    "platform": "ZD8",
    "category": "Model year",
    "title": "2022–2023",
    "summary": "EyeSight on AT; early MT without EyeSight · Standard · — · Early MT/AT tabs; 2022 lamp recall VIN check",
    "sourceUrl": "https://techinfo.subaru.com/stis/doc/warrantyBooklet/2022_war_and_maint_120721.PDF",
    "sourceWorkbook": "Subaru ZD8 BRZ USDM Maintenance Schedules - Community Revised E46 Standard (2).xlsx"
  },
  {
    "slug": "zd8-model-year-2024",
    "platform": "ZD8",
    "category": "Model year",
    "title": "2024",
    "summary": "EyeSight added to manual · tS gets Brembo + STI-tuned Hitachi dampers · tS · tS gets dedicated schedule",
    "sourceUrl": "https://www.prnewswire.com/news-releases/new-performance-focused-2024-subaru-brz-ts-debuts-at-subiefest-california-301883963.html",
    "sourceWorkbook": "Subaru ZD8 BRZ USDM Maintenance Schedules - Community Revised E46 Standard (2).xlsx"
  },
  {
    "slug": "zd8-model-year-2025",
    "platform": "ZD8",
    "category": "Model year",
    "title": "2025",
    "summary": "EyeSight continues · tS hardware · Series.Purple 500, 6MT, Limited-based · Purple maps to standard late 6MT",
    "sourceUrl": "https://www.prnewswire.com/news-releases/subaru-announces-2025-brz-seriespurple-special-edition-302278963.html",
    "sourceWorkbook": "Subaru ZD8 BRZ USDM Maintenance Schedules - Community Revised E46 Standard (2).xlsx"
  },
  {
    "slug": "zd8-model-year-2026",
    "platform": "ZD8",
    "category": "Model year",
    "title": "2026",
    "summary": "EyeSight continues; Premium discontinued · tS hardware · Series.Yellow 350, tS-based · Yellow maps to tS schedule",
    "sourceUrl": "https://www.prnewswire.com/news-releases/subaru-of-america-announces-pricing-on-2026-subaru-brz-302564123.html",
    "sourceWorkbook": "Subaru ZD8 BRZ USDM Maintenance Schedules - Community Revised E46 Standard (2).xlsx"
  },
  {
    "slug": "zd8-performance-variant-ts",
    "platform": "ZD8",
    "category": "Performance variant",
    "title": "tS",
    "summary": "6MT · Gold Brembo 4F/2R · STI-tuned Hitachi · BRZ tS-Yellow 24-26 6MT · Performance trim",
    "sourceUrl": "https://www.prnewswire.com/news-releases/new-performance-focused-2024-subaru-brz-ts-debuts-at-subiefest-california-301883963.html",
    "sourceWorkbook": "Subaru ZD8 BRZ USDM Maintenance Schedules - Community Revised E46 Standard (2).xlsx"
  },
  {
    "slug": "zd8-performance-variant-series-purple",
    "platform": "ZD8",
    "category": "Performance variant",
    "title": "Series.Purple",
    "summary": "6MT · Standard Limited · STI Flexible V-Bar + short shifter · BRZ 24-26 6MT · 500 units",
    "sourceUrl": "https://www.prnewswire.com/news-releases/subaru-announces-2025-brz-seriespurple-special-edition-302278963.html",
    "sourceWorkbook": "Subaru ZD8 BRZ USDM Maintenance Schedules - Community Revised E46 Standard (2).xlsx"
  },
  {
    "slug": "zd8-performance-variant-series-yellow",
    "platform": "ZD8",
    "category": "Performance variant",
    "title": "Series.Yellow",
    "summary": "6MT · Brembo tS · STI-tuned Hitachi · BRZ tS-Yellow 24-26 6MT · 350 units",
    "sourceUrl": "https://www.prnewswire.com/news-releases/subaru-announces-limited-production-2026-subaru-wrx-and-2026-subaru-brz-seriesyellow-sports-cars-at-boxerfest-2025-302553226.html",
    "sourceWorkbook": "Subaru ZD8 BRZ USDM Maintenance Schedules - Community Revised E46 Standard (2).xlsx"
  },
  {
    "slug": "zd8-platform-factory-cadence",
    "platform": "ZD8",
    "category": "Platform",
    "title": "Factory cadence",
    "summary": "FA24 twins have separate brand service booklets. · Use the badge-specific schedule. · Shared issue only where evidence is platform-wide. · Separate severe-use layer. · Toyota 7.5k service points; Subaru 6k/6mo oil. · Do not blend schedules.",
    "sourceUrl": "https://techinfo.subaru.com/stis/doc/warrantyBooklet/2022_war_and_maint_120721.PDF",
    "sourceWorkbook": "Subaru ZD8 BRZ USDM Maintenance Schedules - Community Revised E46 Standard (2).xlsx"
  },
  {
    "slug": "zd8-platform-d-4s-timing-chain",
    "platform": "ZD8",
    "category": "Platform",
    "title": "D-4S / timing chain",
    "summary": "2.4L boxer uses direct + port injection and timing chains. · No timing-belt interval; fuel system is diagnostic/condition based. · No fixed walnut-blasting interval. · Oil-level and pressure monitoring for track. · Core hardware shared. · Use exact MY service data.",
    "sourceUrl": "https://techinfo.subaru.com/stis/doc/ownerManual/MSA5B2606A_STIS.pdf",
    "sourceWorkbook": "Subaru ZD8 BRZ USDM Maintenance Schedules - Community Revised E46 Standard (2).xlsx"
  },
  {
    "slug": "zd8-platform-rtv-pickup",
    "platform": "ZD8",
    "category": "Platform",
    "title": "RTV / pickup",
    "summary": "Excess RTV debris has been documented in some inspections; no official RTV recall located. · Condition/history-driven pickup inspection only. · Community/no-recall card. · Treat separately from track pressure behavior. · Shared discussion. · Do not call every car affected.",
    "sourceUrl": "https://www.youtube.com/watch?v=E35rYvT4t6g",
    "sourceWorkbook": "Subaru ZD8 BRZ USDM Maintenance Schedules - Community Revised E46 Standard (2).xlsx"
  },
  {
    "slug": "zd8-platform-track-oil-pressure",
    "platform": "ZD8",
    "category": "Platform",
    "title": "Track oil pressure",
    "summary": "Instrumented testing found repeatable pressure drops in some high-G right turns. · No street interval. · Track-only evidence. · Log pressure/temp and validate modifications. · Shared platform test. · Not established street defect.",
    "sourceUrl": "https://www.roadandtrack.com/news/a44362621/toyota-gr86-subaru-brz-fa24-potential-starvation-issue/",
    "sourceWorkbook": "Subaru ZD8 BRZ USDM Maintenance Schedules - Community Revised E46 Standard (2).xlsx"
  },
  {
    "slug": "zd8-platform-rear-differential",
    "platform": "ZD8",
    "category": "Platform",
    "title": "Rear differential",
    "summary": "Torsen LSD shared. · Follow brand schedule/preventive layer. · Noise/leak is condition based. · Shorten fluid service for track/drift. · Subaru explicitly replaces 60k/4yr; Toyota normally inspects. · Toyota preventive change is not OEM replacement.",
    "sourceUrl": "https://techinfo.subaru.com/stis/doc/warrantyBooklet/2022_war_and_maint_120721.PDF",
    "sourceWorkbook": "Subaru ZD8 BRZ USDM Maintenance Schedules - Community Revised E46 Standard (2).xlsx"
  },
  {
    "slug": "zd8-platform-adas",
    "platform": "ZD8",
    "category": "Platform",
    "title": "ADAS",
    "summary": "2024+ manual cars gain stereo-camera driver assistance. · Calibration only after relevant repair. · Warnings diagnostic. · Alignment/ride-height changes can trigger calibration needs. · Toyota Active Safety / Subaru EyeSight. · If equipped.",
    "sourceUrl": "https://www.prnewswire.com/news-releases/new-performance-focused-2024-subaru-brz-ts-debuts-at-subiefest-california-301883963.html",
    "sourceWorkbook": "Subaru ZD8 BRZ USDM Maintenance Schedules - Community Revised E46 Standard (2).xlsx"
  }
];
