import { keeperLegalConfig, KEEPER_SUPPORT_EMAIL, LEGAL_LAST_UPDATED, legalPageLabel, PRIVACY_VERSION, TERMS_VERSION, type LegalPageKind } from "./legal";

type LegalPageProps = {
  page: LegalPageKind;
  onOpenAccount: () => void;
};

export function LegalPage({ page, onOpenAccount }: LegalPageProps) {
  const title = legalPageLabel[page];
  return <section className="legal-page" aria-labelledby="legal-page-title">
    <header className="legal-hero">
      <p className="eyebrow">Keeper · public document</p>
      <h1 id="legal-page-title">{title}</h1>
      <p>{page === "contact" ? "Help with your account, garage, vehicle data, purchases, or privacy." : "Clear product policies for using Keeper Auto and managing your information."}</p>
    </header>

    {page === "terms" && <div className="legal-document">
      <p className="legal-version">Terms version {TERMS_VERSION} · Last updated {LEGAL_LAST_UPDATED}</p>
      <section><h2>1. What Keeper provides</h2><p>Keeper is a vehicle ownership, garage organization, maintenance-tracking, and automotive research service. It may display maintenance schedules, specifications, known-issue research, estimated recommendations, automatically matched information, and records entered by owners.</p></section>
      <section><h2>2. Automotive and safety information</h2><p>Keeper is not a mechanic, dealership, manufacturer, vehicle inspection, licensed technician, safety certification, or professional repair advice. Keeper cannot inspect or diagnose your vehicle. Confirm safety-critical decisions with VIN-specific manufacturer guidance, recall information, service documentation, and a qualified automotive professional before operating, maintaining, or repairing a vehicle.</p></section>
      <section><h2>3. Data can vary</h2><p>Automotive information may differ by region, production date, model year, chassis, trim, engine, transmission, previous repairs, manufacturer revisions, recall status, and owner modifications. Keeper does not guarantee that every interval, issue, specification, database entry, or recommendation is complete, error-free, or applicable to every vehicle. A known issue is a research signal, not a diagnosis.</p></section>
      <section><h2>4. Your records and decisions</h2><p>You may enter mileage, maintenance and repair history, costs, notes, fluids, modifications, issue tracking, and other ownership records. You are responsible for the accuracy of information you enter and for decisions made about your vehicle. Keeper does not independently verify that owner-entered work was performed.</p></section>
      <section><h2>5. Account responsibilities</h2><p>Provide accurate signup information, keep your sign-in methods secure, and maintain access to your account. Do not access another person&apos;s garage, disrupt or probe Keeper, evade vehicle limits or paid entitlements, abuse promotions, or automate account creation or redemptions. You are responsible for activity performed through your account unless applicable law provides otherwise.</p></section>
      <section><h2>6. One-time Keeper purchases</h2><p>Keeper Upgrade is currently a $1.99 one-time purchase providing a three-vehicle garage and PDF exports. Keeper Infinite is currently a $4.99 one-time purchase providing unlimited vehicle capacity and PDF exports. These are permanent account entitlements, not subscriptions or recurring billing. A purchase applies to the account used at checkout and covers the described entitlement; it does not promise every unrelated feature Keeper may create in the future.</p></section>
      <section><h2>7. Payments, refunds, and disputes</h2><p>Stripe processes checkout and payment information. Prices and available products are shown before purchase. For billing mistakes, duplicate charges, refund questions, or entitlement problems, contact <a href={`mailto:${KEEPER_SUPPORT_EMAIL}`}>{KEEPER_SUPPORT_EMAIL}</a>. Requests are considered under applicable law, Stripe&apos;s payment rules, and the circumstances of the transaction; these Terms do not remove non-waivable consumer rights.</p></section>
      <section><h2>8. Promotions</h2><p>Keeper may offer limited-quantity promotional access. Current availability and eligibility are determined by Keeper&apos;s product interface and server. Promotions may require a verified account, limit redemption to one per eligible person or account, and be changed, paused, or withdrawn. Keeper may deny or reverse access obtained through fraud, automation, duplicate identities, manipulation, or other abuse, while respecting applicable law.</p></section>
      <section><h2>9. Availability and acceptable use</h2><p>Keeper may update, correct, suspend, or discontinue parts of the service and cannot promise uninterrupted availability. Do not misuse the service, interfere with security controls, scrape it in a way that harms operation, upload unlawful content, or use Keeper to violate another person&apos;s rights.</p></section>
      <section><h2>10. Responsibility and limits</h2><p>Use Keeper as an organizational and informational aid, not as the sole basis for vehicle safety or repair decisions. To the extent permitted by law, Keeper is not responsible for losses caused by relying solely on incomplete or inapplicable vehicle information, inaccurate owner-entered records, ignored manufacturer guidance, unauthorized account access caused by a user&apos;s failure to protect credentials, or third-party services outside Keeper&apos;s control. Nothing here excludes responsibility that cannot legally be limited.</p></section>
      <section><h2>11. Changes and contact</h2><p>Material updates will use a new Terms version and updated date. Continued use may require accepting the current documents. Questions about these Terms can be sent to <a href={`mailto:${KEEPER_SUPPORT_EMAIL}`}>{KEEPER_SUPPORT_EMAIL}</a>.</p></section>
    </div>}

    {page === "privacy" && <div className="legal-document">
      <p className="legal-version">Privacy version {PRIVACY_VERSION} · Last updated {LEGAL_LAST_UPDATED}</p>
      <section><h2>1. Information Keeper processes</h2><p>Keeper processes account details such as email address, display name, authentication identifiers and state, accepted policy versions, and security events. Garage data may include vehicles, mileage, maintenance and repair records, costs, fluids, notes, modifications, tracked issues, export activity, and other ownership records you provide. Keeper also stores purchase entitlements, promotion claims, Stripe customer or checkout references, and limited technical or request information needed to operate, secure, diagnose, and prevent abuse of the service.</p></section>
      <section><h2>2. How information is used</h2><p>Keeper uses this information to authenticate accounts, sync and display garages, match vehicle research, enforce vehicle limits, create exports, complete purchases, grant entitlements, operate promotions, respond to support and privacy requests, protect the service, and investigate errors or abuse.</p></section>
      <section><h2>3. Service providers</h2><p>Supabase provides authentication, database, and server-function infrastructure for account and garage data. Cloudflare hosts and delivers the website and may process ordinary network, security, and diagnostic logs. Stripe processes checkout, payment, fraud-prevention, and payment-status information. Google may act as an identity provider when you choose Google sign-in. Each provider processes information under its own terms and privacy practices.</p></section>
      <section><h2>4. Payments and authentication</h2><p>Keeper does not store full payment-card numbers; Stripe collects and processes card details during checkout. Keeper receives identifiers and status information needed to associate a successful purchase with an account. When you use Google sign-in, Keeper receives identity information needed for authentication and does not receive or store your Google password.</p></section>
      <section><h2>5. Browser and technical data</h2><p>Theme settings, temporary configuration, pending sign-in state, or legacy-garage claim information may be stored in your browser. Hosting, authentication, database, and payment providers may process IP address, device or browser information, request timestamps, and security or error logs as needed to provide and protect their services. Keeper does not describe these operational logs as advertising tracking and does not currently use advertising trackers.</p></section>
      <section><h2>6. Sharing and sale</h2><p>Keeper shares information with service providers only as needed to operate the functions described above, or when required for security, legal compliance, or protection of rights. Keeper does not sell personal information and does not use garage records for third-party behavioral advertising.</p></section>
      <section><h2>7. Data separation and security</h2><p>Keeper uses authentication, owner-scoped database policies, restricted server functions, and other reasonable technical measures to separate account records and limit access. No online service can guarantee absolute security. Protect your sign-in methods and contact Keeper if you suspect unauthorized access.</p></section>
      <section><h2>8. Retention, deletion, and requests</h2><p>Account and garage data are retained while needed to provide Keeper, meet legal or security obligations, resolve disputes, and maintain accurate purchase records. Keeper has an in-app control that records a pending account-deletion request for review; it does not immediately or automatically erase the account. For deletion follow-up, access or correction requests, or other privacy questions, contact <a href={`mailto:${KEEPER_SUPPORT_EMAIL}`}>{KEEPER_SUPPORT_EMAIL}</a>. Applicable rights and necessary verification depend on your location and request.</p></section>
      <section><h2>9. Policy changes</h2><p>Material updates will use a new Privacy version and updated date. If an update requires new consent, Keeper may ask you to review and accept the current documents before continuing account activity.</p></section>
    </div>}

    {page === "contact" && <div className="legal-document">
      <section><h2>Email Keeper support</h2><p>Contact <a href={`mailto:${keeperLegalConfig.supportEmail}`}>{keeperLegalConfig.supportEmail}</a> for account help, vehicle or maintenance-data corrections, technical or PDF export problems, purchase or entitlement issues, privacy requests, and general feedback.</p></section>
      <section><h2>Helpful details</h2><p>Include the email associated with your Keeper account and a concise description of the issue. For a vehicle-data correction, include the make, model, year, trim, engine, transmission, and the source that supports the correction. Do not email passwords or full payment-card numbers.</p></section>
      <section><h2>Support availability</h2><p>Keeper provides email support as a small early-stage service. No phone, physical-office, 24/7, or guaranteed response-time support is currently advertised.</p></section>
    </div>}

    <aside className="legal-account-cta"><div><span>Keeper Profile</span><strong>Your garage, stored under your account.</strong></div><button className="button button-primary" onClick={onOpenAccount}>Open Profile</button></aside>
  </section>;
}
